(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Medium7Engine=api})(this,function(){
'use strict';

const ATOMIC_TYPES=[
  'IN_ROOM','NOT_IN_ROOM','ON_OBJECT','ONLY_PERSON_ON_OBJECT','BESIDE_OBJECT','NOT_BESIDE_OBJECT','CORNER',
  'ALONE_IN_ROOM','ALONE_WITH','EMPTY_ROOM','DIAGONAL_TO_OBJECT','ROW','COLUMN',
  'WEST_OF_OBJECT','EAST_OF_OBJECT','NORTH_OF_OBJECT','SOUTH_OF_OBJECT',
  'WEST_OF_PERSON','EAST_OF_PERSON','NORTH_OF_PERSON','SOUTH_OF_PERSON'
];
const OBJECT_TAGS=['standable','blocking','reflective'];
const OBJECT_RELATIONS=new Set(['ON_OBJECT','ONLY_PERSON_ON_OBJECT','BESIDE_OBJECT','NOT_BESIDE_OBJECT','DIAGONAL_TO_OBJECT','WEST_OF_OBJECT','EAST_OF_OBJECT','NORTH_OF_OBJECT','SOUTH_OF_OBJECT']);
const PERSON_RELATIONS=new Set(['WEST_OF_PERSON','EAST_OF_PERSON','NORTH_OF_PERSON','SOUTH_OF_PERSON','ALONE_WITH']);
const ADVANCED_REASONS=new Set(['row-ownership','column-ownership','multi-row-ownership','multi-column-ownership','intersecting-square-elimination']);

function seedHash(s){let h=2166136261>>>0;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function seededRandom(seed){let a=seedHash(seed);return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function withSeed(seed,fn){const old=Math.random;Math.random=seededRandom(seed);try{return fn()}finally{Math.random=old}}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function rand(n){return Math.floor(Math.random()*n)}
function choose(a){return a[rand(a.length)]}
function same(a,b){return !!a&&!!b&&a.r===b.r&&a.c===b.c}
function cellKey(x){return `${x.r},${x.c}`}
function clone(x){return JSON.parse(JSON.stringify(x))}

function createEngine(N=7){
  if(!Number.isInteger(N)||N<6||N>9)throw Error('N must be an integer from 6 to 9');
  const PEOPLE=Array.from({length:N},(_,i)=>String.fromCharCode(65+i));
  const idx=(r,c)=>r*N+c, cell=i=>({r:Math.floor(i/N),c:i%N});
  let searchCalls=0;
  const generatorStats={candidatePuzzlesEvaluated:0,redundantConstraintCandidates:0,redundantConstraintsDetected:0,zeroConstraintCandidates:0,tagGatingRejected:0,mediumFloorRejected:0,depth2FloorRejected:0,chainBreadthRejected:0,placementBreadthRejected:0};

  function inBounds(r,c){return r>=0&&c>=0&&r<N&&c<N}
  function roomId(P,x){return P.regionOf[x.r][x.c]}
  function roomName(P,x){return P.roomNames[roomId(P,x)]}
  function objectByName(P,name){return (P.objects||[]).find(o=>o.name===name)||null}
  function objectOccurrences(P,name){const o=objectByName(P,name);return o?o.occurrences||[]:[]}
  function objectCells(P,name){return objectOccurrences(P,name).flatMap(o=>o.cells||[])}
  function blockedKeys(P){return new Set((P.objects||[]).filter(o=>o.tags?.includes('blocking')).flatMap(o=>o.occurrences||[]).flatMap(o=>o.cells||[]).map(cellKey))}
  function isBlocked(P,x){return blockedKeys(P).has(cellKey(x))}
  function isPlayable(P,x){return inBounds(x.r,x.c)&&!isBlocked(P,x)}
  function onObject(P,x,name){return objectCells(P,name).some(c=>same(c,x))}
  function allowsBesideOrDirection(o){return !!o&&(o.tags?.includes('standable')||o.tags?.includes('blocking'))}
  function allowsOn(o){return !!o&&o.tags?.includes('standable')&&!o.tags?.includes('blocking')}
  function allowsDiagonal(o){return !!o&&o.tags?.includes('reflective')}

  function roomWall(P,r,c,dr,dc){const nr=r+dr,nc=c+dc;if(!inBounds(nr,nc))return true;return P.regionOf[nr][nc]!==P.regionOf[r][c]}
  function isCornerCell(P,x){return (roomWall(P,x.r,x.c,0,-1)||roomWall(P,x.r,x.c,0,1))&&(roomWall(P,x.r,x.c,-1,0)||roomWall(P,x.r,x.c,1,0))}
  function cornerCells(P){const out=[];for(let r=0;r<N;r++)for(let c=0;c<N;c++){const x={r,c};if(isCornerCell(P,x))out.push({r,c,room:P.roomNames[P.regionOf[r][c]],blocked:isBlocked(P,x)})}return out}

  function besideOccurrence(P,x,occ){return (occ.cells||[]).some(y=>roomId(P,x)===roomId(P,y)&&Math.abs(x.r-y.r)+Math.abs(x.c-y.c)===1)}
  function besideObject(P,x,name){if(onObject(P,x,name))return false;return objectOccurrences(P,name).some(occ=>besideOccurrence(P,x,occ))}
  function directionalToOccurrence(type,x,occ){const rows=occ.cells.map(c=>c.r),cols=occ.cells.map(c=>c.c);if(type==='WEST_OF_OBJECT')return x.c<Math.min(...cols);if(type==='EAST_OF_OBJECT')return x.c>Math.max(...cols);if(type==='NORTH_OF_OBJECT')return x.r<Math.min(...rows);if(type==='SOUTH_OF_OBJECT')return x.r>Math.max(...rows);return false}
  function directionalToObject(P,type,x,name){return objectOccurrences(P,name).some(occ=>directionalToOccurrence(type,x,occ))}
  function directionalToPerson(type,a,b){if(type==='WEST_OF_PERSON')return a.c<b.c;if(type==='EAST_OF_PERSON')return a.c>b.c;if(type==='NORTH_OF_PERSON')return a.r<b.r;if(type==='SOUTH_OF_PERSON')return a.r>b.r;return false}
  function diagonalToObject(P,x,name){return objectCells(P,name).some(y=>!same(x,y)&&Math.abs(x.r-y.r)===Math.abs(x.c-y.c))}

  function constraintList(P,p){return P.constraints?.[p]||[]}
  function allAtomicConstraints(P){const out=[];for(const p of PEOPLE)for(let i=0;i<constraintList(P,p).length;i++)out.push({subject:p,index:i,constraint:constraintList(P,p)[i]});for(let i=0;i<(P.globalConstraints||[]).length;i++)out.push({subject:null,index:i,constraint:P.globalConstraints[i],global:true});return out}
  function atomicConstraintCount(P){return allAtomicConstraints(P).length}

  function requiredTagMode(type){if(type==='ON_OBJECT'||type==='ONLY_PERSON_ON_OBJECT')return'on';if(type==='DIAGONAL_TO_OBJECT')return'diagonal';if(['BESIDE_OBJECT','NOT_BESIDE_OBJECT','WEST_OF_OBJECT','EAST_OF_OBJECT','NORTH_OF_OBJECT','SOUTH_OF_OBJECT'].includes(type))return'physical';return null}
  function constraintTagValid(P,cl){const mode=requiredTagMode(cl.type);if(!mode)return true;const o=objectByName(P,cl.object);if(!o)return false;if(mode==='on')return allowsOn(o);if(mode==='diagonal')return allowsDiagonal(o);return allowsBesideOrDirection(o)}

  function relationAgainstOccurrence(P,cl,x,occ){if(cl.type==='BESIDE_OBJECT'){if(onObject(P,x,cl.object))return false;return besideOccurrence(P,x,occ)}if(cl.type==='NOT_BESIDE_OBJECT'){if(onObject(P,x,cl.object))return true;return !besideOccurrence(P,x,occ)}if(cl.type==='DIAGONAL_TO_OBJECT')return (occ.cells||[]).some(y=>!same(x,y)&&Math.abs(x.r-y.r)===Math.abs(x.c-y.c));if(['WEST_OF_OBJECT','EAST_OF_OBJECT','NORTH_OF_OBJECT','SOUTH_OF_OBJECT'].includes(cl.type))return directionalToOccurrence(cl.type,x,occ);return false}
  function sameObjectPairValid(P,p,cs){if(cs.length<2)return true;const [a,b]=cs;if(!a.object||a.object!==b.object)return true;const occupancy=new Set(['ON_OBJECT','ONLY_PERSON_ON_OBJECT']);const spatial=new Set(['BESIDE_OBJECT','NOT_BESIDE_OBJECT','DIAGONAL_TO_OBJECT','WEST_OF_OBJECT','EAST_OF_OBJECT','NORTH_OF_OBJECT','SOUTH_OF_OBJECT']);if((occupancy.has(a.type)&&spatial.has(b.type))||(occupancy.has(b.type)&&spatial.has(a.type)))return false;if(spatial.has(a.type)&&spatial.has(b.type)){const x=P.solution[p];return objectOccurrences(P,a.object).some(occ=>relationAgainstOccurrence(P,a,x,occ)&&relationAgainstOccurrence(P,b,x,occ))}return true}

  function unaryHolds(P,cl,x){
    if(cl.type==='IN_ROOM')return roomName(P,x)===cl.room;
    if(cl.type==='NOT_IN_ROOM')return roomName(P,x)!==cl.room;
    if(cl.type==='ON_OBJECT'||cl.type==='ONLY_PERSON_ON_OBJECT')return onObject(P,x,cl.object);
    if(cl.type==='BESIDE_OBJECT')return besideObject(P,x,cl.object);
    if(cl.type==='NOT_BESIDE_OBJECT')return !besideObject(P,x,cl.object);
    if(cl.type==='CORNER')return isCornerCell(P,x)&&(!cl.room||roomName(P,x)===cl.room);
    if(cl.type==='ALONE_IN_ROOM')return roomName(P,x)===cl.room;
    if(cl.type==='DIAGONAL_TO_OBJECT')return diagonalToObject(P,x,cl.object);
    if(cl.type==='ROW')return x.r===cl.row;
    if(cl.type==='COLUMN')return x.c===cl.column;
    if(['WEST_OF_OBJECT','EAST_OF_OBJECT','NORTH_OF_OBJECT','SOUTH_OF_OBJECT'].includes(cl.type))return directionalToObject(P,cl.type,x,cl.object);
    if(PERSON_RELATIONS.has(cl.type))return true;
    return true;
  }

  function constraintSatisfied(P,subject,cl,placements){
    if(cl.type==='EMPTY_ROOM')return PEOPLE.every(q=>roomName(P,placements[q])!==cl.room);
    const x=placements[subject];if(!x)return false;
    if(!unaryHolds(P,cl,x))return false;
    if(['WEST_OF_PERSON','EAST_OF_PERSON','NORTH_OF_PERSON','SOUTH_OF_PERSON'].includes(cl.type)){const y=placements[cl.other];return !!y&&directionalToPerson(cl.type,x,y)}
    if(cl.type==='ONLY_PERSON_ON_OBJECT')return PEOPLE.every(q=>q===subject||!onObject(P,placements[q],cl.object));
    if(cl.type==='ALONE_IN_ROOM')return PEOPLE.every(q=>q===subject||roomName(P,placements[q])!==cl.room);
    if(cl.type==='ALONE_WITH'){const y=placements[cl.other];if(!y||roomId(P,x)!==roomId(P,y))return false;const rid=roomId(P,x);return PEOPLE.every(q=>q===subject||q===cl.other||roomId(P,placements[q])!==rid)}
    return true;
  }

  function baseCandidates(P){const out=[];for(let r=0;r<N;r++)for(let c=0;c<N;c++){const x={r,c};if(isPlayable(P,x))out.push(x)}return out}
  function ownCandidates(P,p){return baseCandidates(P).filter(x=>constraintList(P,p).every(cl=>unaryHolds(P,cl,x))&&(P.globalConstraints||[]).every(cl=>cl.type!=='EMPTY_ROOM'||roomName(P,x)!==cl.room))}
  function validateStoredSolutionAgainstClues(P){for(const p of PEOPLE)for(const cl of constraintList(P,p))if(!constraintSatisfied(P,p,cl,P.solution))return{valid:false,person:p,constraint:cl};for(const cl of P.globalConstraints||[])if(!constraintSatisfied(P,null,cl,P.solution))return{valid:false,constraint:cl};return{valid:true}}
  function fullValid(P,placements){if(!placements||PEOPLE.some(p=>!placements[p]))return false;const rows=new Set,cols=new Set;for(const p of PEOPLE){const x=placements[p];if(!isPlayable(P,x)||rows.has(x.r)||cols.has(x.c))return false;rows.add(x.r);cols.add(x.c)}if(rows.size!==N||cols.size!==N)return false;for(const p of PEOPLE)for(const cl of constraintList(P,p))if(!constraintSatisfied(P,p,cl,placements))return false;for(const cl of P.globalConstraints||[])if(!constraintSatisfied(P,null,cl,placements))return false;return true}

  function binaryHolds(type,a,b){return directionalToPerson(type,a,b)}
  function initialDomainsWithTrace(P){const D={},events=[];for(const p of PEOPLE)D[p]=new Set(baseCandidates(P).map(x=>idx(x.r,x.c)));for(const p of PEOPLE)for(const cl of constraintList(P,p)){const bad=new Set([...D[p]].filter(i=>!unaryHolds(P,cl,cell(i))));remove(D,p,bad,'own-constraint-filtering',cl,events,{phase:'own'})}for(const cl of P.globalConstraints||[])if(cl.type==='EMPTY_ROOM')for(const p of PEOPLE){const bad=new Set([...D[p]].filter(i=>roomName(P,cell(i))===cl.room));remove(D,p,bad,'own-constraint-filtering',cl,events,{phase:'global'})}events.forEach(e=>e.round=0);return{domains:D,events}}
  function cloneDomains(D){return Object.fromEntries(Object.entries(D).map(([p,s])=>[p,new Set(s)]))}
  function remove(D,p,ids,reason,cl,events,meta={}){const before=[...D[p]],rm=before.filter(i=>ids.has(i));if(!rm.length)return false;rm.forEach(i=>D[p].delete(i));events.push({reason,constraintType:cl?.type||null,subject:p,removed:rm.map(cell),before:before.map(cell),after:[...D[p]].map(cell),...meta});if(before.length>1&&D[p].size===1)events.push({reason:'forced-placement',subject:p,cell:cell([...D[p]][0]),sourceReason:reason,constraintType:cl?.type||null,...meta});return true}
  function propagateBinary(P,D,subject,cl,events){const ref=cl.other;if(!D[ref])return false;let changed=false;const badA=new Set([...D[subject]].filter(ai=>![...D[ref]].some(bi=>binaryHolds(cl.type,cell(ai),cell(bi)))));const inverse={WEST_OF_PERSON:'EAST_OF_PERSON',EAST_OF_PERSON:'WEST_OF_PERSON',NORTH_OF_PERSON:'SOUTH_OF_PERSON',SOUTH_OF_PERSON:'NORTH_OF_PERSON'}[cl.type];const badB=new Set([...D[ref]].filter(bi=>![...D[subject]].some(ai=>binaryHolds(inverse,cell(bi),cell(ai)))));if(remove(D,subject,badA,'relational-deduction',cl,events,{reference:ref}))changed=true;if(remove(D,ref,badB,'relational-deduction',cl,events,{reference:subject}))changed=true;return changed}
  function propagateCardinality(P,D,subject,cl,events){let changed=false;if(cl.type==='ONLY_PERSON_ON_OBJECT'){const obj=new Set(objectCells(P,cl.object).map(x=>idx(x.r,x.c)));for(const q of PEOPLE)if(q!==subject&&remove(D,q,new Set([...D[q]].filter(i=>obj.has(i))),'relational-deduction',cl,events,{reference:subject}))changed=true;return changed}if(cl.type==='ALONE_IN_ROOM'){for(const q of PEOPLE)if(q!==subject){const bad=new Set([...D[q]].filter(i=>roomName(P,cell(i))===cl.room));if(remove(D,q,bad,'relational-deduction',cl,events,{reference:subject,room:cl.room}))changed=true}return changed}if(cl.type==='ALONE_WITH'){const ref=cl.other;let badA=new Set([...D[subject]].filter(ai=>![...D[ref]].some(bi=>roomId(P,cell(ai))===roomId(P,cell(bi))))),badB=new Set([...D[ref]].filter(bi=>![...D[subject]].some(ai=>roomId(P,cell(ai))===roomId(P,cell(bi)))));if(remove(D,subject,badA,'relational-deduction',cl,events,{reference:ref}))changed=true;if(remove(D,ref,badB,'relational-deduction',cl,events,{reference:subject}))changed=true;const common=[...new Set([...D[subject]].map(i=>roomId(P,cell(i))))].filter(r=>[...D[ref]].some(i=>roomId(P,cell(i))===r));if(common.length===1){const rid=common[0];for(const q of PEOPLE)if(q!==subject&&q!==ref){const bad=new Set([...D[q]].filter(i=>roomId(P,cell(i))===rid));if(remove(D,q,bad,'relational-deduction',cl,events,{reference:subject,room:P.roomNames[rid]}))changed=true}}return changed}return false}
  function combinations(a,k){const out=[];(function rec(start,cur){if(cur.length===k){out.push(cur.slice());return}for(let i=start;i<=a.length-(k-cur.length);i++){cur.push(a[i]);rec(i+1,cur);cur.pop()}})(0,[]);return out}
  function axisValues(D,p,axis){return new Set([...D[p]].map(i=>axis==='row'?cell(i).r:cell(i).c))}
  function applyOwnership(P,D,axis,events){let changed=false;for(let k=2;k<PEOPLE.length;k++)for(const owners of combinations(PEOPLE,k)){if(owners.some(p=>D[p].size<2||axisValues(D,p,axis).size<2))continue;const values=new Set;owners.forEach(p=>axisValues(D,p,axis).forEach(v=>values.add(v)));if(values.size!==k)continue;const reason=axis==='row'?(k===2?'row-ownership':'multi-row-ownership'):(k===2?'column-ownership':'multi-column-ownership');for(const q of PEOPLE)if(!owners.includes(q)){const bad=new Set([...D[q]].filter(i=>values.has(axis==='row'?cell(i).r:cell(i).c)));if(remove(D,q,bad,reason,null,events,{owners:owners.slice(),values:[...values].sort((a,b)=>a-b),axis}))changed=true}}return changed}
  function applyIntersectingSquare(P,D,events){let changed=false;for(const source of PEOPLE){if(D[source].size<2||D[source].size>3)continue;const supports=[...D[source]].map(cell);for(const q of PEOPLE)if(q!==source){const bad=new Set([...D[q]].filter(i=>{const y=cell(i);return supports.every(x=>x.r===y.r||x.c===y.c)}));if(remove(D,q,bad,'intersecting-square-elimination',null,events,{sourcePerson:source,supports}))changed=true}}return changed}
  function propagateDomains(P,input=null){const init=input?{domains:cloneDomains(input),events:[]} : initialDomainsWithTrace(P),D=init.domains,events=init.events;let changed=true,guard=0;while(changed&&guard++<100){changed=false;const roundStart=events.length;for(const p of PEOPLE)if(D[p].size===1){const x=cell([...D[p]][0]);for(const q of PEOPLE)if(q!==p){if(remove(D,q,new Set([...D[q]].filter(i=>cell(i).r===x.r)),'row-elimination',null,events,{sourcePerson:p,row:x.r}))changed=true;if(remove(D,q,new Set([...D[q]].filter(i=>cell(i).c===x.c)),'column-elimination',null,events,{sourcePerson:p,column:x.c}))changed=true}}for(const p of PEOPLE)for(const cl of constraintList(P,p)){if(['WEST_OF_PERSON','EAST_OF_PERSON','NORTH_OF_PERSON','SOUTH_OF_PERSON'].includes(cl.type)){if(propagateBinary(P,D,p,cl,events))changed=true}else if(['ONLY_PERSON_ON_OBJECT','ALONE_IN_ROOM','ALONE_WITH'].includes(cl.type)){if(propagateCardinality(P,D,p,cl,events))changed=true}}for(let r=0;r<N;r++){const owners=PEOPLE.filter(p=>[...D[p]].some(i=>cell(i).r===r));if(owners.length===1){const p=owners[0];if(remove(D,p,new Set([...D[p]].filter(i=>cell(i).r!==r)),'row-occupancy',null,events,{row:r}))changed=true}}for(let c=0;c<N;c++){const owners=PEOPLE.filter(p=>[...D[p]].some(i=>cell(i).c===c));if(owners.length===1){const p=owners[0];if(remove(D,p,new Set([...D[p]].filter(i=>cell(i).c!==c)),'column-occupancy',null,events,{column:c}))changed=true}}if(applyIntersectingSquare(P,D,events))changed=true;if(applyOwnership(P,D,'row',events))changed=true;if(applyOwnership(P,D,'column',events))changed=true;for(let i=roundStart;i<events.length;i++)if(events[i].round===undefined)events[i].round=guard;if(PEOPLE.some(p=>D[p].size===0))break}return{domains:D,events,contradiction:PEOPLE.some(p=>D[p].size===0),solved:PEOPLE.every(p=>D[p].size===1),rounds:guard}}
  function strictSolve(P){const before=searchCalls,res=propagateDomains(P),after=searchCalls;if(after!==before)throw Error('Human propagation invoked search');const placements={};if(res.solved)for(const p of PEOPLE)placements[p]=cell([...res.domains[p]][0]);const ok=res.solved&&!res.contradiction&&fullValid(P,placements);return{ok,reason:ok?'complete deterministic propagation':'No complete deterministic solve; guessing would be required',trace:res.events,placements,domains:res.domains,searchCalls:after-before,rounds:res.rounds}}

  function partialConsistent(P,assigned){for(const [p,x] of Object.entries(assigned)){for(const cl of constraintList(P,p)){if(['WEST_OF_PERSON','EAST_OF_PERSON','NORTH_OF_PERSON','SOUTH_OF_PERSON'].includes(cl.type)&&assigned[cl.other]&&!directionalToPerson(cl.type,x,assigned[cl.other]))return false;if(cl.type==='ONLY_PERSON_ON_OBJECT')for(const [q,y] of Object.entries(assigned))if(q!==p&&onObject(P,y,cl.object))return false;if(cl.type==='ALONE_IN_ROOM')for(const [q,y] of Object.entries(assigned))if(q!==p&&roomName(P,y)===cl.room)return false;if(cl.type==='ALONE_WITH'){if(assigned[cl.other]&&roomId(P,x)!==roomId(P,assigned[cl.other]))return false;const rid=roomId(P,x);for(const [q,y] of Object.entries(assigned))if(q!==p&&q!==cl.other&&roomId(P,y)===rid)return false}}}for(const cl of P.globalConstraints||[])if(cl.type==='EMPTY_ROOM')for(const y of Object.values(assigned))if(roomName(P,y)===cl.room)return false;return true}
  function countSolutions(P,limit=2){searchCalls++;const domains=Object.fromEntries(PEOPLE.map(p=>[p,ownCandidates(P,p)]));let count=0;const assigned={},usedR=new Set,usedC=new Set;function rec(){if(count>=limit)return;if(Object.keys(assigned).length===N){if(fullValid(P,assigned))count++;return}let best=null,bestOpts=null;for(const p of PEOPLE)if(!assigned[p]){const opts=domains[p].filter(x=>!usedR.has(x.r)&&!usedC.has(x.c));if(!best||opts.length<bestOpts.length){best=p;bestOpts=opts}}if(!bestOpts.length)return;for(const x of bestOpts){assigned[best]=x;usedR.add(x.r);usedC.add(x.c);if(partialConsistent(P,assigned))rec();usedR.delete(x.r);usedC.delete(x.c);delete assigned[best];if(count>=limit)return}}rec();return count}

  function roomConnected(P,rid){const cells=[];for(let r=0;r<N;r++)for(let c=0;c<N;c++)if(P.regionOf[r][c]===rid)cells.push({r,c});if(!cells.length)return false;const want=new Set(cells.map(cellKey)),seen=new Set([cellKey(cells[0])]),q=[cells[0]];while(q.length){const x=q.shift();for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const y={r:x.r+dr,c:x.c+dc},k=cellKey(y);if(inBounds(y.r,y.c)&&want.has(k)&&!seen.has(k)){seen.add(k);q.push(y)}}}return seen.size===want.size}
  function occurrenceConnected(occ){if(!occ.cells?.length)return false;const want=new Set(occ.cells.map(cellKey)),seen=new Set([cellKey(occ.cells[0])]),q=[occ.cells[0]];while(q.length){const x=q.shift();for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const y={r:x.r+dr,c:x.c+dc},k=cellKey(y);if(want.has(k)&&!seen.has(k)){seen.add(k);q.push(y)}}}return seen.size===want.size}
  function validateObjects(P){const occupied=new Map;for(const o of P.objects||[]){const tags=o.tags||[];if(tags.some(t=>!OBJECT_TAGS.includes(t)))return false;if(tags.includes('standable')&&tags.includes('blocking'))return false;if(![1,2,3].includes(o.footprintSize))return false;for(const occ of o.occurrences||[]){if(occ.cells.length!==o.footprintSize||!occurrenceConnected(occ))return false;const rooms=new Set(occ.cells.map(x=>roomId(P,x)));if(rooms.size!==1)return false;for(const x of occ.cells){if(!inBounds(x.r,x.c))return false;const k=cellKey(x);if(occupied.has(k))return false;occupied.set(k,o.name)}}}return true}
  function validateStructural(P,{allowEmptyPersonConstraints=false}={}){if(!P||P.n!==N||P.people?.length!==N||P.regionOf?.length!==N||P.regionOf.some(row=>row.length!==N))return{ok:false,reason:'shape'};const roomIds=new Set(P.regionOf.flat());if([...roomIds].some(r=>!Number.isInteger(r)||r<0)||[...roomIds].some(r=>!roomConnected(P,r)))return{ok:false,reason:'room connectivity'};if(!validateObjects(P))return{ok:false,reason:'object invariants'};for(let r=0;r<N;r++)if(!Array.from({length:N},(_,c)=>({r,c})).some(x=>isPlayable(P,x)))return{ok:false,reason:'row has no playable cell'};for(let c=0;c<N;c++)if(!Array.from({length:N},(_,r)=>({r,c})).some(x=>isPlayable(P,x)))return{ok:false,reason:'column has no playable cell'};for(const p of PEOPLE){const n=constraintList(P,p).length;if(!allowEmptyPersonConstraints&&n<1)return{ok:false,reason:'missing atomic constraint',person:p};if(n>2)return{ok:false,reason:'too many atomic constraints',person:p};if(!sameObjectPairValid(P,p,constraintList(P,p)))return{ok:false,reason:'same-object clue pair quality'};for(const cl of constraintList(P,p)){if(!ATOMIC_TYPES.includes(cl.type)||!constraintTagValid(P,cl))return{ok:false,reason:'invalid constraint/tag'}}}for(const cl of P.globalConstraints||[])if(!ATOMIC_TYPES.includes(cl.type)||cl.type!=='EMPTY_ROOM')return{ok:false,reason:'invalid global constraint'};return{ok:true}}

  function generateRegionGrid(){const roomCount=Math.max(4,Math.min(N+1,N-1+rand(3))),cells=Array.from({length:N*N},(_,i)=>cell(i)),seeds=shuffle(cells).slice(0,roomCount),R=Array.from({length:N},()=>Array(N).fill(-1)),front=seeds.map((x,i)=>({x,id:i}));seeds.forEach((x,i)=>R[x.r][x.c]=i);let remaining=N*N-roomCount,guard=0;while(remaining&&guard++<N*N*20){const choice=front[rand(front.length)],dirs=shuffle([[1,0],[-1,0],[0,1],[0,-1]]);let grown=false;for(const [dr,dc] of dirs){const r=choice.x.r+dr,c=choice.x.c+dc;if(inBounds(r,c)&&R[r][c]===-1){R[r][c]=choice.id;front.push({x:{r,c},id:choice.id});remaining--;grown=true;break}}if(!grown)front.splice(front.indexOf(choice),1);if(!front.length&&remaining)return null}if(remaining)return null;const sizes=Array(roomCount).fill(0);R.flat().forEach(x=>sizes[x]++);if(Math.min(...sizes)<2)return null;return R}
  function makeSolution(P){const rows=shuffle([...Array(N).keys()]),cols=shuffle([...Array(N).keys()]);return Object.fromEntries(PEOPLE.map((p,i)=>[p,{r:rows[i],c:cols[i]}]))}
  function growFootprint(P,start,size,used,avoid){const rid=roomId(P,start),cells=[start],seen=new Set([cellKey(start)]);while(cells.length<size){const edges=[];for(const x of cells)for(const [dr,dc] of shuffle([[1,0],[-1,0],[0,1],[0,-1]])){const y={r:x.r+dr,c:x.c+dc},k=cellKey(y);if(inBounds(y.r,y.c)&&roomId(P,y)===rid&&!seen.has(k)&&!used.has(k)&&!avoid.has(k))edges.push(y)}if(!edges.length)return null;const y=choose(edges);cells.push(y);seen.add(cellKey(y))}return cells}
  function placeOccurrence(P,size,used,avoid,preferred=[]){const starts=shuffle([...preferred,...baseCandidates({regionOf:P.regionOf,objects:[],roomNames:P.roomNames})]).filter((x,i,a)=>a.findIndex(y=>same(x,y))===i&&!used.has(cellKey(x))&&!avoid.has(cellKey(x)));for(const start of starts.slice(0,N*N)){const cells=growFootprint(P,start,size,used,avoid);if(cells)return cells}return null}
  function makeObjects(P){const used=new Set,solutionKeys=new Set(Object.values(P.solution).map(cellKey)),objects=[];let normal=1,locked=1,target=N+2+rand(3);for(let i=0;i<target;i++){const blocking=Math.random()<0.34,name=blocking?`Locked ${locked++}`:`Object ${normal++}`,footprintSize=1+rand(3),tags=[blocking?'blocking':'standable'];if(Math.random()<0.38)tags.push('reflective');const occurrences=[],count=Math.random()<0.34?2:1;for(let j=0;j<count;j++){const avoid=blocking?solutionKeys:new Set;let preferred=[];if(!blocking&&Math.random()<0.42)preferred=shuffle(Object.values(P.solution));const cells=placeOccurrence(P,footprintSize,used,avoid,preferred);if(!cells)break;cells.forEach(x=>used.add(cellKey(x)));occurrences.push({id:`${name.replace(/ /g,'_')}_${j+1}`,cells})}if(occurrences.length)objects.push({id:name.replace(/ /g,'_'),name,footprintSize,tags,occurrences})}P.objects=objects;P.blocked=[...blockedKeys(P)].map(k=>{const [r,c]=k.split(',').map(Number);return{r,c}})}

  function roomOccupants(P){const out=Object.fromEntries(P.roomNames.map(r=>[r,[]]));for(const p of PEOPLE)out[roomName(P,P.solution[p])].push(p);return out}
  function objectOccupants(P,name){return PEOPLE.filter(p=>onObject(P,P.solution[p],name))}
  function factPool(P,p,forbid=new Set){const x=P.solution[p],out=[],add=cl=>{if(forbid.has(cl.type))return;if(constraintTagValid(P,cl)&&constraintSatisfied(P,p,cl,P.solution))out.push(cl);else if(OBJECT_RELATIONS.has(cl.type)&&!constraintTagValid(P,cl))generatorStats.tagGatingRejected++};const rn=roomName(P,x),occ=roomOccupants(P);add({type:'IN_ROOM',room:rn});const others=P.roomNames.filter(r=>r!==rn);shuffle(others).slice(0,2).forEach(room=>add({type:'NOT_IN_ROOM',room}));if(isCornerCell(P,x))add({type:'CORNER',room:rn});if(occ[rn].length===1)add({type:'ALONE_IN_ROOM',room:rn});if(occ[rn].length===2){const other=occ[rn].find(q=>q!==p);add({type:'ALONE_WITH',other})}add({type:'ROW',row:x.r});add({type:'COLUMN',column:x.c});for(const q of PEOPLE)if(q!==p){const y=P.solution[q];if(x.c<y.c)add({type:'WEST_OF_PERSON',other:q});if(x.c>y.c)add({type:'EAST_OF_PERSON',other:q});if(x.r<y.r)add({type:'NORTH_OF_PERSON',other:q});if(x.r>y.r)add({type:'SOUTH_OF_PERSON',other:q})}for(const o of P.objects){if(allowsOn(o)&&onObject(P,x,o.name)){add({type:'ON_OBJECT',object:o.name});if(objectOccupants(P,o.name).length===1)add({type:'ONLY_PERSON_ON_OBJECT',object:o.name})}if(allowsBesideOrDirection(o)){if(besideObject(P,x,o.name))add({type:'BESIDE_OBJECT',object:o.name});else if(!onObject(P,x,o.name)&&Math.random()<0.45)add({type:'NOT_BESIDE_OBJECT',object:o.name});for(const t of ['WEST_OF_OBJECT','EAST_OF_OBJECT','NORTH_OF_OBJECT','SOUTH_OF_OBJECT'])if(directionalToObject(P,t,x,o.name)&&Math.random()<0.55)add({type:t,object:o.name})}if(allowsDiagonal(o)&&diagonalToObject(P,x,o.name))add({type:'DIAGONAL_TO_OBJECT',object:o.name})}const seen=new Set;return out.filter(cl=>{const k=JSON.stringify(cl);if(seen.has(k))return false;seen.add(k);return true})}
  function optionSet(P,p,forbid){const pool=factPool(P,p,forbid),opts=[];const test=cs=>{if(cs.length>2||!sameObjectPairValid(P,p,cs))return;const Q={...P,constraints:{...P.constraints,[p]:cs}};const n=ownCandidates(Q,p).length;if(n>=2&&n<=Math.max(9,N+1))opts.push({constraints:cs,candidates:n,relational:cs.some(c=>PERSON_RELATIONS.has(c.type)||['ONLY_PERSON_ON_OBJECT','ALONE_IN_ROOM'].includes(c.type))})};for(const a of pool)test([a]);for(let i=0;i<pool.length;i++)for(let j=i+1;j<pool.length;j++)test([pool[i],pool[j]]);const seen=new Set;return shuffle(opts.filter(o=>{const k=JSON.stringify(o.constraints);if(seen.has(k))return false;seen.add(k);return true})).sort((a,b)=>(Math.abs(a.candidates-4)+(a.relational?0:0.5))-(Math.abs(b.candidates-4)+(b.relational?0:0.5))).slice(0,110)}

  function advancedDeductionKey(e){if(!ADVANCED_REASONS.has(e.reason))return null;if(e.reason==='intersecting-square-elimination'){const supports=(e.supports||[]).map(cellKey).sort().join(';');return`${e.reason}|${e.round||0}|${e.sourcePerson||''}|${supports}`}const owners=(e.owners||[]).slice().sort().join(','),values=(e.values||[]).slice().sort((a,b)=>a-b).join(',');return`${e.reason}|${e.round||0}|${owners}|${values}`}
  function influenceSources(e){const out=new Set;if(e.sourcePerson)out.add(e.sourcePerson);if(e.reference)out.add(e.reference);if(Array.isArray(e.owners))e.owners.forEach(p=>out.add(p));return out}
  function analyzeMediumStructure(P,h){const t=h?.trace||[],groups=new Map;for(let i=0;i<t.length;i++){const e=t[i],key=advancedDeductionKey(e);if(!key)continue;if(!groups.has(key))groups.set(key,{key,reason:e.reason,indices:[],targets:new Set,participants:new Set});const g=groups.get(key);g.indices.push(i);if(e.subject){g.targets.add(e.subject);g.participants.add(e.subject)}influenceSources(e).forEach(p=>g.participants.add(p))}let material=0;const depPlacements=new Set,chainPeople=new Set,materialKeys=[];for(const g of groups.values()){const tainted=new Set(g.targets),localPeople=new Set(g.participants),localPlacements=new Set;let contributed=false,start=Math.min(...g.indices);for(let i=start+1;i<t.length;i++){const e=t[i];if(advancedDeductionKey(e)===g.key)continue;if(e.reason==='forced-placement'&&tainted.has(e.subject)){contributed=true;localPlacements.add(e.subject);localPeople.add(e.subject)}const sources=influenceSources(e),sourceTainted=[...sources].some(p=>tainted.has(p));if(sourceTainted){contributed=true;sources.forEach(p=>localPeople.add(p));if(e.subject){localPeople.add(e.subject);tainted.add(e.subject)}}}if(contributed){material++;materialKeys.push(g.key);localPlacements.forEach(p=>depPlacements.add(p));localPeople.forEach(p=>chainPeople.add(p))}}return{advancedDeductionCount:groups.size,ownershipCount:[...groups.values()].filter(g=>g.reason!=='intersecting-square-elimination').length,intersectionCount:[...groups.values()].filter(g=>g.reason==='intersecting-square-elimination').length,materialAdvancedDeductions:material,advancedDependentPlacements:depPlacements.size,advancedDependentPlacementPeople:[...depPlacements].sort(),multiPersonChainPeople:chainPeople.size,multiPersonChainParticipants:[...chainPeople].sort(),materialAdvancedKeys:materialKeys}}
  function metrics(P,h){const initialCandidates=Object.fromEntries(PEOPLE.map(p=>[p,ownCandidates(P,p).length])),t=h.trace||[],count=r=>t.filter(e=>e.reason===r).length,base={initialCandidates,directClueSingles:PEOPLE.filter(p=>initialCandidates[p]===1).length,multiCandidatePeople:PEOPLE.filter(p=>initialCandidates[p]>1).length,rowColumnEliminations:count('row-elimination')+count('column-elimination'),rowOwnershipDeductions:count('row-ownership'),columnOwnershipDeductions:count('column-ownership'),multiRowOwnershipDeductions:count('multi-row-ownership'),multiColumnOwnershipDeductions:count('multi-column-ownership'),relationalDeductions:count('relational-deduction'),intersectingSquareDeductions:count('intersecting-square-elimination'),forcedPlacements:count('forced-placement'),totalDeterministicTraceLength:t.length,dependencyDepth:Math.max(0,...t.map(e=>e.round||0)),constraintFamilies:[...new Set(allAtomicConstraints(P).map(x=>x.constraint.type))].sort(),totalAtomicConstraintCount:atomicConstraintCount(P)};return{...base,...analyzeMediumStructure(P,h)}}
  function mediumAcceptance(m){const reasons=[];if(m.directClueSingles!==0)reasons.push('initial direct singles');if(m.multiCandidatePeople!==N)reasons.push('not all people unresolved');if(m.advancedDeductionCount<2)reasons.push('advanced deductions < 2');if(m.materialAdvancedDeductions<1)reasons.push('material advanced < 1');if(m.dependencyDepth<2)reasons.push('depth < 2');if(m.multiPersonChainPeople<4)reasons.push('chain people < 4');if(m.advancedDependentPlacements<4)reasons.push('advanced placements < 4');if(m.dependencyDepth===2&&(m.multiPersonChainPeople<5||m.advancedDependentPlacements<5||m.advancedDeductionCount<3))reasons.push('depth-2 floor');return{ok:!reasons.length,reasons}}
  function classifyMedium(m){const a=mediumAcceptance(m);if(!a.ok)return'TOO EASY';if(m.dependencyDepth>=3&&m.materialAdvancedDeductions>=2&&m.multiPersonChainPeople>=5&&m.advancedDependentPlacements>=4)return'CLEAR MEDIUM';if(m.dependencyDepth===2&&m.advancedDeductionCount>=4&&m.multiPersonChainPeople>=6&&m.advancedDependentPlacements>=6)return'CLEAR MEDIUM';return'BORDERLINE'}

  function removeAtomic(P,item){const Q=clone(P);if(item.global)Q.globalConstraints.splice(item.index,1);else Q.constraints[item.subject].splice(item.index,1);return Q}
  function validateNecessity(P){const redundantConstraints=[];for(const item of allAtomicConstraints(P)){const Q=removeAtomic(P,item),n=countSolutions(Q,2);if(n<2)redundantConstraints.push({...item,solutionCountWithoutConstraint:n})}return redundantConstraints.length?{ok:false,redundant:redundantConstraints[0],redundantConstraints,redundantCount:redundantConstraints.length,solutionCountWithoutConstraint:redundantConstraints[0].solutionCountWithoutConstraint}:{ok:true,redundantConstraints:[],redundantCount:0}}
  function validateSampledCandidatePolicy(P){const structural=validateStructural(P);if(!structural.ok)return{ok:false,reason:structural.reason,structural};const necessity=validateNecessity(P);if(!necessity.ok)return{ok:false,reason:'redundant atomic constraint',necessity};return{ok:true,necessity}}

  function deriveMetadata(P){const occ=roomOccupants(P),pairs=[],singletons=[],empty_rooms=[];for(const [room,ps] of Object.entries(occ)){if(ps.length===2)pairs.push({room,people:ps.slice().sort()});else if(ps.length===1)singletons.push({room,person:ps[0]});else if(ps.length===0)empty_rooms.push(room)}const on_object=[];for(const p of PEOPLE)for(const o of P.objects)if(allowsOn(o)&&onObject(P,P.solution[p],o.name))on_object.push({person:p,object:o.name});const negative_clues=allAtomicConstraints(P).filter(x=>x.constraint.type.startsWith('NOT_')).map(x=>({person:x.subject,constraint:x.constraint}));return{pairs,singletons,empty_rooms,on_object,negative_clues}}
  function diagonalRays(P){const out=[];for(const o of P.objects.filter(allowsDiagonal))for(const occ of o.occurrences)for(const origin of occ.cells)for(const [dr,dc,name] of [[-1,-1,'NW'],[-1,1,'NE'],[1,-1,'SW'],[1,1,'SE']]){const cells=[];let r=origin.r+dr,c=origin.c+dc;while(inBounds(r,c)){cells.push({r,c});r+=dr;c+=dc}out.push({object:o.name,occurrence:occ.id,origin:{...origin},direction:name,cells})}return out}
  function lineCells(P){const out=[];for(const p of PEOPLE)for(const cl of constraintList(P,p)){if(cl.type==='ROW')out.push({person:p,type:'ROW',index:cl.row,cells:Array.from({length:N},(_,c)=>({r:cl.row,c}))});if(cl.type==='COLUMN')out.push({person:p,type:'COLUMN',index:cl.column,cells:Array.from({length:N},(_,r)=>({r,c:cl.column}))})}return out}
  function roomBoundaryEdges(P){const out=[],seen=new Set;for(let r=0;r<N;r++)for(let c=0;c<N;c++)for(const [dr,dc,side] of [[-1,0,'N'],[1,0,'S'],[0,-1,'W'],[0,1,'E']]){if(!roomWall(P,r,c,dr,dc))continue;const nr=r+dr,nc=c+dc;if(inBounds(nr,nc)){const a=idx(r,c),b=idx(nr,nc),key=`${Math.min(a,b)}-${Math.max(a,b)}`;if(seen.has(key))continue;seen.add(key);out.push({cell:{r,c},side,neighbor:{r:nr,c:nc},outer:false})}else out.push({cell:{r,c},side,neighbor:null,outer:true})}return out}
  function deriveRenderData(P){return{corner_cells:cornerCells(P),diagonal_rays:diagonalRays(P),line_cells:lineCells(P),room_boundary_edges:roomBoundaryEdges(P)}}

  function printConstraint(cl,p){if(cl.type==='IN_ROOM')return`${p} was in ${cl.room}.`;if(cl.type==='NOT_IN_ROOM')return`${p} was not in ${cl.room}.`;if(cl.type==='ON_OBJECT')return`${p} was on ${cl.object}.`;if(cl.type==='ONLY_PERSON_ON_OBJECT')return`${p} was the only person on ${cl.object}.`;if(cl.type==='BESIDE_OBJECT')return`${p} was directly beside ${cl.object}.`;if(cl.type==='NOT_BESIDE_OBJECT')return`${p} was not directly beside ${cl.object}.`;if(cl.type==='CORNER')return`${p} was in a corner of ${cl.room}.`;if(cl.type==='ALONE_IN_ROOM')return`${p} was alone in ${cl.room}.`;if(cl.type==='ALONE_WITH')return`${p} was alone with ${cl.other}.`;if(cl.type==='DIAGONAL_TO_OBJECT')return`${p} was diagonal to ${cl.object}.`;if(cl.type==='ROW')return`${p} was in row ${cl.row+1}.`;if(cl.type==='COLUMN')return`${p} was in column ${cl.column+1}.`;if(cl.type.endsWith('_OF_OBJECT'))return`${p} was ${cl.type.split('_OF_')[0].toLowerCase()} of ${cl.object}.`;if(cl.type.endsWith('_OF_PERSON'))return`${p} was ${cl.type.split('_OF_')[0].toLowerCase()} of ${cl.other}.`;return cl.type}
  function printPersonConstraints(P,p){const cs=constraintList(P,p);if(cs.length===2){const room=cs.find(c=>c.type==='IN_ROOM'),not=cs.find(c=>c.type==='NOT_BESIDE_OBJECT');if(room&&not)return[`${p} was in ${room.room}, but not directly beside ${not.object}.`]}return cs.map(c=>printConstraint(c,p))}

  function objectiveDirectlyStated(P,obj){if(obj.type==='WHERE_PERSON'){return ownCandidates(P,obj.person).length<3}if(obj.type==='WHO_SHARED_ROOM')return constraintList(P,obj.person).some(c=>c.type==='ALONE_WITH');if(obj.type==='WHO_ON_OBJECT')return PEOPLE.some(p=>constraintList(P,p).some(c=>['ON_OBJECT','ONLY_PERSON_ON_OBJECT'].includes(c.type)&&c.object===obj.object));if(obj.type==='WHICH_ROOM_EMPTY')return(P.globalConstraints||[]).some(c=>c.type==='EMPTY_ROOM');return true}
  function validateObjective(P,obj){if(!obj||!['WHERE_PERSON','WHO_SHARED_ROOM','WHICH_ROOM_EMPTY','WHO_ON_OBJECT'].includes(obj.type))return false;if(obj.type==='WHERE_PERSON'||obj.type==='WHO_SHARED_ROOM'){if(!PEOPLE.includes(obj.person))return false}if(obj.type==='WHO_ON_OBJECT'&&!objectByName(P,obj.object))return false;return!objectiveDirectlyStated(P,obj)}
  function objectiveAnswer(P,obj){if(obj.type==='WHERE_PERSON')return{...P.solution[obj.person]};if(obj.type==='WHO_SHARED_ROOM'){const rid=roomId(P,P.solution[obj.person]);return PEOPLE.filter(p=>p!==obj.person&&roomId(P,P.solution[p])===rid)}if(obj.type==='WHICH_ROOM_EMPTY')return deriveMetadata(P).empty_rooms.slice();if(obj.type==='WHO_ON_OBJECT')return PEOPLE.filter(p=>onObject(P,P.solution[p],obj.object));return null}function assignObjective(P){const eligible=shuffle(PEOPLE.filter(p=>ownCandidates(P,p).length>=3));for(const p of eligible){const obj={type:'WHERE_PERSON',person:p};if(validateObjective(P,obj))return obj}return null}

  function normalizeForbid(x){const k=String(x).trim().toUpperCase();if(k==='DIAGONAL')return'DIAGONAL_TO_OBJECT';return k}function validateRequest(req={}){const out={n:req.n??N,difficulty:req.difficulty??'medium',require:req.require||{},forbid:req.forbid||[]};if(!Number.isInteger(out.n)||out.n<6||out.n>9)return{ok:false,reason:'n must be 6..9'};if(out.difficulty!=='medium')return{ok:false,reason:'only medium generation is implemented in this checkpoint'};for(const [k,v] of Object.entries(out.require))if(!['empty_rooms','pairs'].includes(k)||!Number.isInteger(v)||v<0)return{ok:false,reason:'invalid require'};const forbid=out.forbid.map(normalizeForbid);for(const x of forbid)if(!ATOMIC_TYPES.includes(x))return{ok:false,reason:`invalid forbid ${x}`};return{ok:true,request:{...out,forbid}}}
  function requestSatisfied(P,req){const m=P.metadata||deriveMetadata(P);if(req.require.empty_rooms!==undefined&&m.empty_rooms.length!==req.require.empty_rooms)return false;if(req.require.pairs!==undefined&&m.pairs.length!==req.require.pairs)return false;return true}

  function buildBoard(){const R=generateRegionGrid();if(!R)return null;const roomCount=Math.max(...R.flat())+1,P={version:2,n:N,difficulty:'medium',people:[...PEOPLE],regionOf:R,roomNames:Array.from({length:roomCount},(_,i)=>`R${i+1}`),objects:[],constraints:Object.fromEntries(PEOPLE.map(p=>[p,[]])),globalConstraints:[]};P.solution=makeSolution(P);makeObjects(P);const s=validateStructural(P,{allowEmptyPersonConstraints:true});return s.ok?P:null}
  function selectConstraints(P,req,maxSelections=650){const forbid=new Set(req.forbid||[]),options={};for(const p of PEOPLE){options[p]=optionSet(P,p,forbid);if(!options[p].length)return null}for(let pick=1;pick<=maxSelections;pick++){generatorStats.candidatePuzzlesEvaluated++;P.constraints=Object.fromEntries(PEOPLE.map(p=>{const pool=options[p],top=pool.slice(0,Math.min(36,pool.length));return[p,choose(top).constraints]}));if(PEOPLE.some(p=>constraintList(P,p).length===0)){generatorStats.zeroConstraintCandidates++;continue}const structural=validateStructural(P);if(!structural.ok){if(structural.reason==='invalid constraint/tag')generatorStats.tagGatingRejected++;continue}const stored=validateStoredSolutionAgainstClues(P);if(!stored.valid)continue;const h=strictSolve(P);if(!h.ok)continue;const m=metrics(P,h),accept=mediumAcceptance(m);if(!accept.ok){generatorStats.mediumFloorRejected++;if(accept.reasons.includes('depth-2 floor'))generatorStats.depth2FloorRejected++;if(accept.reasons.includes('chain people < 4'))generatorStats.chainBreadthRejected++;if(accept.reasons.includes('advanced placements < 4'))generatorStats.placementBreadthRejected++;continue}if(countSolutions(P,2)!==1)continue;const policy=validateSampledCandidatePolicy(P);if(!policy.ok){if(policy.reason==='redundant atomic constraint'){generatorStats.redundantConstraintCandidates++;generatorStats.redundantConstraintsDetected+=policy.necessity.redundantCount}if(policy.reason==='missing atomic constraint')generatorStats.zeroConstraintCandidates++;continue}P.selectionAttempts=pick;P.validation={solutions:1,human:h,metrics:m,necessity:policy.necessity,mediumAcceptance:accept,mediumClassification:classifyMedium(m)};return P}return null}
  function finalizePuzzle(P,req,id,generationAttempts){P.metadata=deriveMetadata(P);if(!requestSatisfied(P,req))return null;P.objective=assignObjective(P);if(!P.objective)return null;P.render=deriveRenderData(P);P.puzzleId=id;P.generationAttempts=generationAttempts;return P}
  function generateById(id,maxGenerationAttempts=1800,request={n:N,difficulty:'medium',require:{},forbid:[]}){const vr=validateRequest(request);if(!vr.ok)throw Error(vr.reason);if(vr.request.n!==N)return createEngine(vr.request.n).generateById(id,maxGenerationAttempts,vr.request);return withSeed(id,()=>{for(let attempt=1;attempt<=maxGenerationAttempts;attempt++){const P=buildBoard();if(!P)continue;const selected=selectConstraints(P,vr.request);if(!selected)continue;const final=finalizePuzzle(selected,vr.request,id,attempt);if(final)return final}return null})}
  function validate(P,{checkNecessity=true}={}){const structural=validateStructural(P);if(!structural.ok)return structural;const stored=validateStoredSolutionAgainstClues(P);if(!stored.valid)return{ok:false,reason:'stored solution constraint mismatch',stored};if(!fullValid(P,P.solution))return{ok:false,reason:'stored solution invalid'};const h=strictSolve(P);if(!h.ok)return{ok:false,reason:h.reason,human:h};const solutions=countSolutions(P,2);if(solutions!==1)return{ok:false,reason:`solution count ${solutions}`,solutions};const m=metrics(P,h),accept=mediumAcceptance(m);if(!accept.ok)return{ok:false,reason:`medium structure: ${accept.reasons.join('; ')}`,metrics:m};let necessity={ok:true};if(checkNecessity){necessity=validateNecessity(P);if(!necessity.ok)return{ok:false,reason:'redundant atomic constraint',necessity}}return{ok:true,solutions,human:h,metrics:m,necessity,mediumClassification:classifyMedium(m)}}

  function resetSearchCallCount(){searchCalls=0}function getSearchCallCount(){return searchCalls}function getGeneratorStats(){return{...generatorStats}}function resetGeneratorStats(){for(const k of Object.keys(generatorStats))generatorStats[k]=0}

  return{version:2,N,PEOPLE,ATOMIC_TYPES,OBJECT_TAGS,createEngine,roomWall,isCornerCell,cornerCells,objectByName,objectOccurrences,objectCells,onObject,besideObject,directionalToObject,directionalToPerson,diagonalToObject,constraintList,atomicConstraintCount,constraintTagValid,sameObjectPairValid,unaryHolds,constraintSatisfied,baseCandidates,ownCandidates,validateStoredSolutionAgainstClues,fullValid,initialDomainsWithTrace,propagateDomains,strictSolve,applyOwnership,applyIntersectingSquare,countSolutions,validateObjects,validateStructural,validateNecessity,validateSampledCandidatePolicy,deriveMetadata,deriveRenderData,diagonalRays,lineCells,roomBoundaryEdges,printConstraint,printPersonConstraints,validateObjective,objectiveAnswer,assignObjective,validateRequest,generateById,validate,metrics,analyzeMediumStructure,mediumAcceptance,classifyMedium,resetSearchCallCount,getSearchCallCount,getGeneratorStats,resetGeneratorStats};
}

const api=createEngine(7);api.createEngine=createEngine;api.ATOMIC_TYPES=ATOMIC_TYPES;api.OBJECT_TAGS=OBJECT_TAGS;return api;
});
