'use strict';
const assert=require('assert'),E=require('../engine/easy-6x6-attribution.js'),PPL=E.PEOPLE,R=E.regionGrid();
const I=(r,c)=>r*6+c,ALL=Array.from({length:36},(_,i)=>i);
function P(){return{profile:'easy-3',people:[...PPL],victim:'F',regionOf:R,roomNames:['Library','Study','Gallery','Foyer','Archive','Lounge'],objects:[],clues:Object.fromEntries(PPL.map(p=>[p,[]])),globalRules:[]}}
function D(x){return Object.fromEntries(PPL.map(p=>[p,new Set(x[p])]))}
let n=0;function t(name,fn){fn();n++;console.log('PASS',name)}
t('A meaningful relational singleton',()=>{let p=P();p.clues.A=[{type:'westOfPerson',person:'B'}];let d=D({A:[I(0,0),I(0,4)],B:[I(1,1),I(1,3)],C:[I(2,2),I(2,5)],D:[I(3,0),I(3,4)],E:[I(4,1),I(4,5)],F:[I(5,2),I(5,3)]}),r=E.propagateDomains(p,d),e=r.events.find(e=>e.deductionType==='relational-propagation'&&e.subject==='A'&&e.producedSingleton);assert(e);assert.equal(e.contributedToProgress,true);console.log('TRACE_SINGLETON',JSON.stringify(e))});
t('B meaningful relational chain to occupancy singleton',()=>{let p=P();p.clues.A=[{type:'westOfPerson',person:'C'}];let d=D({A:[I(0,4),I(2,0),I(3,1)],B:[I(0,1),I(4,2)],C:[I(1,2),I(1,3)],D:[I(2,4),I(3,5)],E:[I(4,4),I(5,5)],F:[I(2,5),I(5,3)]}),r=E.propagateDomains(p,d),rel=r.events.find(e=>e.deductionType==='relational-propagation'&&e.subject==='A'&&e.removed.some(x=>x.r===0&&x.c===4)),occ=r.events.find(e=>e.deductionType==='row-column-occupancy'&&e.subject==='B'&&e.producedSingleton&&e.dependsOn.includes(rel.sequence));assert(rel&&occ);assert.equal(rel.producedSingleton,false);assert.equal(rel.contributedToProgress,true);console.log('TRACE_CHAIN',JSON.stringify({relational:rel,occupancy:occ}))});
t('C irrelevant relational elimination stays irrelevant',()=>{let p=P();p.clues.A=[{type:'westOfPerson',person:'B'}];let d=D({A:[I(0,5),I(2,0),I(3,1)],B:[I(1,2),I(1,4)],C:ALL,D:ALL,E:ALL,F:ALL}),r=E.propagateDomains(p,d),rel=r.events.find(e=>e.deductionType==='relational-propagation'&&e.subject==='A'&&e.removed.some(x=>x.r===0&&x.c===5));assert(rel);assert.equal(rel.producedSingleton,false);assert.equal(rel.contributedToProgress,false);assert.equal(r.events.filter(e=>e.deductionType==='relational-propagation'&&e.contributedToProgress).length,0);console.log('TRACE_IRRELEVANT',JSON.stringify(rel))});
t('D human attribution has zero search calls',()=>{let p=P();p.clues.A=[{type:'westOfPerson',person:'B'}];let d=D({A:[I(0,0),I(0,4)],B:[I(1,1),I(1,3)],C:[I(2,2),I(2,5)],D:[I(3,0),I(3,4)],E:[I(4,1),I(4,5)],F:[I(5,2),I(5,3)]});E.resetSearchCallCount();E.strictSolve(p,d);assert.equal(E.getSearchCallCount(),0)});
t('metrics distinguish clue presence elimination and meaningful use',()=>{let p=P();p.clues.A=[{type:'westOfPerson',person:'B'}];let d=D({A:[I(0,5),I(2,0),I(3,1)],B:[I(1,2),I(1,4)],C:ALL,D:ALL,E:ALL,F:ALL}),h={trace:E.propagateDomains(p,d).events},m=E.metrics(p,h);assert.equal(m.relationalCluesPresent,1);assert(m.relationalEliminationEvents>0);assert.equal(m.meaningfulRelationalDeductions,0)});
console.log('ATTRIBUTION TESTS PASSED:',n);
