'use strict';
const assert=require('assert');
const E=require('../engine/easy-6x6-profiles.js');
const people=E.PEOPLE,R=E.regionGrid(),rooms=['Library','Study','Gallery','Foyer','Archive','Lounge'];
function base(){return{profile:'easy-1',people:[...people],victim:'F',regionOf:R,roomNames:rooms,objects:[],clues:Object.fromEntries(people.map(p=>[p,[]])),globalRules:[]}}
function assignment(cells){return Object.fromEntries(people.map((p,i)=>[p,cells[i]]))}function ok(P,p,cl,a){return E.clueSatisfied(P,p,cl,a)}let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name)}
const A=assignment([{r:0,c:0},{r:1,c:1},{r:2,c:2},{r:3,c:3},{r:4,c:4},{r:5,c:5}]);
test('onObject',()=>{let P=base();P.objects=[{name:'O',r:0,c:0}];assert(ok(P,'A',{type:'onObject',object:'O'},A));assert(!ok(P,'B',{type:'onObject',object:'O'},A))});
test('onlyOnObject exact v7.1 semantics',()=>{let P=base();P.objects=[{name:'O',r:0,c:0},{name:'O',r:2,c:2}];assert(ok(P,'A',{type:'onlyOnObject',object:'O'},assignment([{r:0,c:0},{r:1,c:1},{r:2,c:3},{r:3,c:2},{r:4,c:4},{r:5,c:5}])));assert(!ok(P,'A',{type:'onlyOnObject',object:'O'},A));assert(!ok(P,'B',{type:'onlyOnObject',object:'O'},A))});
test('besideObject same-room boundary',()=>{let P=base();P.objects=[{name:'O',r:0,c:0}];assert(ok(P,'A',{type:'besideObject',object:'O'},{...A,A:{r:0,c:1}}));P.objects=[{name:'O',r:0,c:2}];assert(!ok(P,'A',{type:'besideObject',object:'O'},{...A,A:{r:0,c:3}}));P.objects=[{name:'O',r:0,c:0}];assert(!ok(P,'A',{type:'besideObject',object:'O'},{...A,A:{r:1,c:1}}))});
test('notBesideObject',()=>{let P=base();P.objects=[{name:'O',r:0,c:0}];assert(!ok(P,'A',{type:'notBesideObject',object:'O'},{...A,A:{r:0,c:1}}));assert(ok(P,'A',{type:'notBesideObject',object:'O'},{...A,A:{r:1,c:1}}))});
test('room / roomNotBesideObject',()=>{let P=base();P.objects=[{name:'O',r:0,c:0}];assert(ok(P,'A',{type:'room',room:R[0][1]},{...A,A:{r:0,c:1}}));assert(ok(P,'A',{type:'roomNotBesideObject',room:R[1][1],object:'O'},{...A,A:{r:1,c:1}}));assert(!ok(P,'A',{type:'roomNotBesideObject',room:R[0][1],object:'O'},{...A,A:{r:0,c:1}}))});
test('corner',()=>{let P=base();assert(ok(P,'A',{type:'corner',room:R[0][0]},{...A,A:{r:0,c:0}}));assert(!ok(P,'A',{type:'corner',room:R[0][0]},{...A,A:{r:0,c:1}}))});
test('diagonal',()=>{let P=base();P.objects=[{name:'O',r:2,c:2}];assert(ok(P,'A',{type:'diagonal',object:'O'},{...A,A:{r:0,c:0}}));assert(!ok(P,'A',{type:'diagonal',object:'O'},{...A,A:{r:0,c:1}}))});
test('row / column',()=>{let P=base();assert(ok(P,'A',{type:'row',row:0},A));assert(!ok(P,'A',{type:'row',row:1},A));assert(ok(P,'A',{type:'column',column:0},A));assert(!ok(P,'A',{type:'column',column:1},A))});
test('object directions',()=>{let P=base();P.objects=[{name:'O',r:3,c:3}];for(const [t,x] of [['westOfObject',{r:3,c:1}],['eastOfObject',{r:3,c:4}],['northOfObject',{r:1,c:3}],['southOfObject',{r:4,c:3}]])assert(ok(P,'A',{type:t,object:'O'},{...A,A:x}));assert(!ok(P,'A',{type:'westOfObject',object:'O'},{...A,A:{r:3,c:4}}))});
test('person directions / besidePerson',()=>{let P=base(),a={...A,A:{r:0,c:0},B:{r:0,c:1}};assert(ok(P,'A',{type:'westOfPerson',person:'B'},a));assert(!ok(P,'A',{type:'eastOfPerson',person:'B'},a));assert(ok(P,'A',{type:'besidePerson',person:'B'},a));a.B={r:0,c:3};assert(!ok(P,'A',{type:'besidePerson',person:'B'},a));assert(E.binaryHolds(P,'northOfPerson',{r:1,c:1},{r:2,c:1}));assert(E.binaryHolds(P,'southOfPerson',{r:2,c:1},{r:1,c:1}))});
test('notWithPerson',()=>{let P=base(),a={...A,A:{r:0,c:0},B:{r:0,c:3}};assert(ok(P,'A',{type:'notWithPerson',person:'B'},a));a.B={r:1,c:1};assert(!ok(P,'A',{type:'notWithPerson',person:'B'},a))});
test('alone',()=>{let P=base(),a=assignment([{r:0,c:0},{r:0,c:3},{r:2,c:2},{r:3,c:3},{r:4,c:4},{r:5,c:5}]);assert(ok(P,'A',{type:'alone'},a));a.B={r:1,c:1};assert(!ok(P,'A',{type:'alone'},a))});
test('aloneInRooms',()=>{let P=base(),a=assignment([{r:0,c:0},{r:0,c:3},{r:2,c:2},{r:3,c:3},{r:4,c:4},{r:5,c:5}]);assert(ok(P,'A',{type:'aloneInRooms',rooms:[R[0][0],5]},a));assert(!ok(P,'A',{type:'aloneInRooms',rooms:[2,3]},a));a.B={r:1,c:1};assert(!ok(P,'A',{type:'aloneInRooms',rooms:[R[0][0],5]},a))});
test('aloneWithPerson',()=>{let P=base(),a=assignment([{r:0,c:0},{r:1,c:1},{r:0,c:3},{r:2,c:3},{r:4,c:4},{r:5,c:5}]);assert(ok(P,'A',{type:'aloneWithPerson',person:'B'},a));a.C={r:1,c:2};assert(!ok(P,'A',{type:'aloneWithPerson',person:'B'},a));a.B={r:0,c:3};assert(!ok(P,'A',{type:'aloneWithPerson',person:'B'},a))});
test('westOfPerson support propagation trace',()=>{let P=base();P.clues.A=[{type:'westOfPerson',person:'B'}];let D={A:new Set([0,4]),B:new Set([7,9]),C:new Set([14,15]),D:new Set([20,21]),E:new Set([28,29]),F:new Set([34,35])};let r=E.propagateDomains(P,D);assert.deepEqual([...r.domains.A],[0]);let ev=r.events.find(e=>e.reason==='relational'&&e.clueType==='westOfPerson'&&e.subject==='A');assert(ev);assert(ev.removed.some(x=>x.r===0&&x.c===4));assert(ev.before.length===2&&ev.after.length===1)});
test('onlyOnObject domain propagation',()=>{let P=base();P.objects=[{name:'O',r:0,c:0},{name:'O',r:2,c:2}];P.clues.A=[{type:'onlyOnObject',object:'O'}];let D={A:new Set([0,14]),B:new Set([7,14]),C:new Set([2,14]),D:new Set([21]),E:new Set([28]),F:new Set([35])};let r=E.propagateDomains(P,D);assert(!r.domains.B.has(14)&&!r.domains.C.has(14));assert(r.events.some(e=>e.clueType==='onlyOnObject'))});
test('alone propagation',()=>{let P=base();P.clues.A=[{type:'alone'}];let D={A:new Set([0]),B:new Set([7,9]),C:new Set([14]),D:new Set([21]),E:new Set([28]),F:new Set([35])};let r=E.propagateDomains(P,D);assert(!r.domains.B.has(7))});
test('aloneWithPerson propagation',()=>{let P=base();P.clues.A=[{type:'aloneWithPerson',person:'B'}];let D={A:new Set([0]),B:new Set([7,9]),C:new Set([2,14]),D:new Set([21]),E:new Set([28]),F:new Set([35])};let r=E.propagateDomains(P,D);assert.deepEqual([...r.domains.B],[7]);assert(!r.domains.C.has(2))});
test('human path has zero search calls',()=>{let P=base();P.solution=A;P.clues={A:[{type:'row',row:0},{type:'column',column:0}],B:[{type:'row',row:1},{type:'column',column:1}],C:[{type:'row',row:2},{type:'column',column:2}],D:[{type:'row',row:3},{type:'column',column:3}],E:[{type:'row',row:4},{type:'column',column:4}],F:[{type:'victim'}]};E.resetSearchCallCount();E.strictSolve(P);assert.equal(E.getSearchCallCount(),0)});
console.log(`SEMANTIC TESTS PASSED: ${passed}`);
