'use strict';const assert=require('assert'),E=require('../engine/easy-6x6-profiles.js'),PPL=E.PEOPLE,R=E.regionGrid();
function P(){return{profile:'easy-1',people:[...PPL],victim:'F',regionOf:R,roomNames:['Library','Study','Gallery','Foyer','Archive','Lounge'],objects:[],clues:Object.fromEntries(PPL.map(p=>[p,[]])),globalRules:[]}}function A(xs){return Object.fromEntries(PPL.map((p,i)=>[p,xs[i]]))}const diag=A([{r:0,c:0},{r:1,c:1},{r:2,c:2},{r:3,c:3},{r:4,c:4},{r:5,c:5}]);let n=0;function t(s,f){f();n++;console.log('PASS',s)}function s(P,p,c,a){return E.clueSatisfied(P,p,c,a)}
t('unary object/room/spatial families',()=>{let p=P();p.objects=[{name:'O',r:2,c:2}];assert(s(p,'A',{type:'onObject',object:'O'},{...diag,A:{r:2,c:2}}));assert(s(p,'A',{type:'diagonal',object:'O'},{...diag,A:{r:0,c:0}}));assert(s(p,'A',{type:'row',row:0},diag));assert(s(p,'A',{type:'column',column:0},diag));assert(s(p,'A',{type:'room',room:R[0][0]},diag));assert(s(p,'A',{type:'corner',room:R[0][0]},diag));for(const [type,x] of [['westOfObject',{r:2,c:1}],['eastOfObject',{r:2,c:3}],['northOfObject',{r:1,c:2}],['southOfObject',{r:3,c:2}]])assert(s(p,'A',{type,object:'O'},{...diag,A:x}))});
t('beside exact same-room semantics',()=>{let p=P();p.objects=[{name:'O',r:0,c:0}];assert(s(p,'A',{type:'besideObject',object:'O'},{...diag,A:{r:0,c:1}}));assert(!s(p,'A',{type:'besideObject',object:'O'},{...diag,A:{r:1,c:1}}));p.objects=[{name:'O',r:0,c:2}];assert(!s(p,'A',{type:'besideObject',object:'O'},{...diag,A:{r:0,c:3}}))});
t('negative object families',()=>{let p=P();p.objects=[{name:'O',r:0,c:0}];assert(!s(p,'A',{type:'notBesideObject',object:'O'},{...diag,A:{r:0,c:1}}));assert(s(p,'A',{type:'notBesideObject',object:'O'},{...diag,A:{r:1,c:1}}));assert(s(p,'A',{type:'roomNotBesideObject',room:R[1][1],object:'O'},{...diag,A:{r:1,c:1}}));assert(!s(p,'A',{type:'roomNotBesideObject',room:R[0][1],object:'O'},{...diag,A:{r:0,c:1}}))});
t('onlyOnObject v7.1 truth table',()=>{let p=P();p.objects=[{name:'O',r:0,c:0},{name:'O',r:2,c:2}];let a=A([{r:0,c:0},{r:1,c:1},{r:2,c:3},{r:3,c:2},{r:4,c:4},{r:5,c:5}]);assert(s(p,'A',{type:'onlyOnObject',object:'O'},a));assert(!s(p,'A',{type:'onlyOnObject',object:'O'},diag));assert(!s(p,'B',{type:'onlyOnObject',object:'O'},diag))});
t('person binary families',()=>{let p=P(),a={...diag,A:{r:0,c:0},B:{r:0,c:1}};assert(s(p,'A',{type:'westOfPerson',person:'B'},a));assert(!s(p,'A',{type:'eastOfPerson',person:'B'},a));assert(s(p,'A',{type:'besidePerson',person:'B'},a));assert(E.binaryHolds(p,'northOfPerson',{r:1,c:1},{r:2,c:1}));assert(E.binaryHolds(p,'southOfPerson',{r:2,c:1},{r:1,c:1}));a.B={r:0,c:3};assert(s(p,'A',{type:'notWithPerson',person:'B'},a));a.B={r:1,c:1};assert(!s(p,'A',{type:'notWithPerson',person:'B'},a))});
t('alone and aloneInRooms cardinality',()=>{let p=P(),a=A([{r:0,c:0},{r:0,c:3},{r:2,c:2},{r:3,c:3},{r:4,c:4},{r:5,c:5}]);assert(s(p,'A',{type:'alone'},a));assert(s(p,'A',{type:'aloneInRooms',rooms:[R[0][0],5]},a));a.B={r:1,c:1};assert(!s(p,'A',{type:'alone'},a));assert(!s(p,'A',{type:'aloneInRooms',rooms:[R[0][0],5]},a))});
t('aloneWithPerson exact two-person room',()=>{let p=P(),a=A([{r:0,c:0},{r:1,c:1},{r:0,c:3},{r:2,c:3},{r:4,c:4},{r:5,c:5}]);assert(s(p,'A',{type:'aloneWithPerson',person:'B'},a));a.C={r:1,c:2};assert(!s(p,'A',{type:'aloneWithPerson',person:'B'},a));a.B={r:0,c:3};assert(!s(p,'A',{type:'aloneWithPerson',person:'B'},a))});
t('westOfPerson arc propagation with debug trace',()=>{let p=P();p.clues.A=[{type:'westOfPerson',person:'B'}];let D={A:new Set([0,4]),B:new Set([7,9]),C:new Set([14,15]),D:new Set([20,21]),E:new Set([28,29]),F:new Set([34,35])},r=E.propagateDomains(p,D),e=r.events.find(e=>e.reason==='relational'&&e.clueType==='westOfPerson'&&e.subject==='A');assert.deepEqual([...r.domains.A],[0]);assert(e&&e.removed.some(x=>x.c===4)&&e.before.length===2&&e.after.length===1);console.log('TRACE',JSON.stringify(e))});
t('onlyOnObject propagates exclusivity to others',()=>{let p=P();p.objects=[{name:'O',r:0,c:0},{name:'O',r:2,c:2}];p.clues.A=[{type:'onlyOnObject',object:'O'}];let D={A:new Set([0,14]),B:new Set([7,14]),C:new Set([2,14]),D:new Set([20,21]),E:new Set([28,29]),F:new Set([34,35])},r=E.propagateDomains(p,D);assert(!r.domains.B.has(14)&&!r.domains.C.has(14));assert(r.events.some(e=>e.clueType==='onlyOnObject'))});
t('alone propagation',()=>{let p=P();p.clues.A=[{type:'alone'}];let D={A:new Set([0]),B:new Set([7,9]),C:new Set([14,15]),D:new Set([20,21]),E:new Set([28,29]),F:new Set([34,35])},r=E.propagateDomains(p,D);assert(!r.domains.B.has(7));assert(r.events.some(e=>e.clueType==='alone'))});
t('aloneWithPerson support propagation',()=>{let p=P();p.clues.A=[{type:'aloneWithPerson',person:'B'}];let D={A:new Set([0]),B:new Set([7,9]),C:new Set([2,14]),D:new Set([20,21]),E:new Set([28,29]),F:new Set([34,35])},r=E.propagateDomains(p,D);assert.deepEqual([...r.domains.B],[7]);assert(!r.domains.C.has(2))});
t('human solver cannot leak into backtracking',()=>{let p=P();p.solution=diag;p.clues={A:[{type:'row',row:0},{type:'column',column:0}],B:[{type:'row',row:1},{type:'column',column:1}],C:[{type:'row',row:2},{type:'column',column:2}],D:[{type:'row',row:3},{type:'column',column:3}],E:[{type:'row',row:4},{type:'column',column:4}],F:[{type:'victim'}]};E.resetSearchCallCount();E.strictSolve(p);assert.equal(E.getSearchCallCount(),0)});
console.log('SEMANTIC TESTS PASSED:',n);