'use strict';
const assert=require('assert'),E=require('../engine/easy-6x6-profiles.js'),PPL=E.PEOPLE,R=E.regionGrid();
const rooms=['Library','Study','Gallery','Foyer','Archive','Lounge'];
function base(){return{profile:'easy-1',people:[...PPL],victim:'F',regionOf:R,roomNames:rooms,objects:[],clues:Object.fromEntries(PPL.map(p=>[p,[]])),globalRules:[]}}
function asn(xs){return Object.fromEntries(PPL.map((p,i)=>[p,xs[i]]))}const A=asn([{r:0,c:0},{r:1,c:1},{r:2,c:2},{r:3,c:3},{r:4,c:4},{r:5,c:5}]);let n=0;function t(name,f){f();n++;console.log('PASS',name)}function sat(P,p,c,a){return E.clueSatisfied(P,p,c,a)}
t('onObject',()=>{let P=base();P.objects=[{name:'O',r:0,c:0}];assert(sat(P,'A',{type:'onObject',object:'O'},A));assert(!sat(P,'B',{type:'onObject',object:'O'},A))});
t('onlyOnObject v7.1',()=>{let P=base();P.objects=[{name:'O',r:0,c:0},{name:'O',r:2,c:2}];assert(sat(P,'A',{type:'onlyOnObject',object:'O'},asn([{r:0,c:0},{r:1,c:1},{r:2,c:3},{r:3,c:2},{r:4,c:4},{r:5,c:5}])));assert(!sat(P,'A',{type:'onlyOnObject',object:'O'},A));assert(!sat(P,'B',{type:'onlyOnObject',object:'O'},A))});
t('besideObject same-room boundary',()=>{let P=base();P.objects=[{name:'O',r:0,c:0}];assert(sat(P,'A',{type:'besideObject',object:'O'},{...A,A:{r:0,c:1}}));P.objects=[{name:'O',r:0,c:2}];assert(!sat(P,'A',{type:'besideObject',object:'O'},{...A,A:{r:0,c:3}}));P.objects=[{name:'O',r:0,c:0}];assert(!sat(P,'A',{type:'besideObject',object:'O'},{...A,A:{r:1,c:1}}))});
t('notBesideObject',()=>{let P=base();P.objects=[{name:'O',r:0,c:0}];assert(!sat(P,'A',{type:'notBesideObject',object:'O'},{...A,A:{r:0,c:1}}));assert(sat(P,'A',{type:'notBesideObject',object:'O'},{...A,A:{r:1,c:1}}))});
t('room and roomNotBesideObject',()=>{let P=base();P.objects=[{name:'O',r:0,c:0}];assert(sat(P,'A',{type:'room',room:R[0][1]},{...A,A:{r:0,c:1}}));assert(sat(P,'A',{type:'roomNotBesideObject',room:R[1][1],object:'O'},{...A,A:{r:1,c:1}}));assert(!sat(P,'A',{type:'roomNotBesideObject',room:R[0][1],object:'O'},{...A,A:{r:0,c:1}}))});
t('corner',()=>{let P=base();assert(sat(P,'A',{type:'corner',room:R[0][0]},{...A,A:{r:0,c:0}}));assert(!sat(P,'A',{type:'corner',room:R[0][0]},{...A,A:{r:0,c:1}}))});
t('diagonal',()=>{let P=base();P.objects=[{name:'O',r:2,c:2}];assert(sat(P,'A',{type:'diagonal',object:'O'},{...A,A:{r:0,c:0}}));assert(!sat(P,'A',{type:'diagonal',object:'O'},{...A,A:{r:0,c:1}}))});
t('row column',()=>{let P=base();assert(sat(P,'A',{type:'row',row:0},A));assert(!sat(P,'A',{type:'row',row:1},A));assert(sat(P,'A',{type:'column',column:0},A));assert(!sat(P,'A',{type:'column',column:1},A))});
t('object directions',()=>{let P=base();P.objects=[{name:'O',r:3,c:3}];for(const [type,x] of [['westOfObject',{r:3,c:1}],['eastOfObject',{r:3,c:4}],['northOfObject',{r:1,c:3}],['southOfObject',{r:4,c:3}]])assert(sat(P,'A',{type,object:'O'},{...A,A:x}));assert(!sat(P,'A',{type:'westOfObject',object:'O'},{...A,A:{r:3,c:4}}))});
t('person directions and besidePerson',()=>{let P=base(),a={...A,A:{r:0,c:0},B:{r:0,c:1}};assert(sat(P,'A',{type:'westOfPerson',person:'B'},a));assert(!sat(P,'A',{type:'eastOfPerson',person:'B'},a));assert(sat(P,'A',{type:'besidePerson',person:'B'},a));a.B={r:0,c:3};assert(!sat(P,'A',{type:'besidePerson',person:'B'},a));assert(E.binaryHolds(P,'northOfPerson',{r:1,c:1},{r:2,c:1}));assert(E.binaryHolds(P,'southOfPerson',{r:2,c:1},{r:1,c:1}))});
t('notWithPerson',()=>{let P=base(),a={...A,A:{r:0,c:0},B:{r:0,c:3}};assert(sat(P,'A',{type:'notWithPerson',person:'B'},a));a.B={r:1,c:1};assert(!sat(P,'A',{type:'notWithPerson',person:'B'},a))});
t('alone',()=>{let P=base(),a=asn([{r:0,c:0},{r:0,c:3},{r:2,c:2},{r:3,c:3},{r:4,c:4},{r:5,c:5}]);assert(sat(P,'A',{type:'alone'},a));a.B={r:1,c:1};assert(!sat(P,'A',{type:'alone'},a))});
t('aloneInRooms',()=>{let P=base(),a=asn([{r:0,c:0},{r:0,c:3},{r:2,c:2},{r:3,c:3},{r:4,c:4},{r:5,c:5}]);assert(sat(P,'A',{type:'aloneInRooms',rooms:[R[0][0],5]},a));assert(!sat(P,'A',{type:'aloneInRooms',rooms:[2,3]},a));a.B={r:1,c:1};assert(!sat(P,'A',{type:'aloneInRooms',rooms:[R[0][0],5]},a))});
t('aloneWithPerson',()=>{let P=base(),a=asn([{r:0,c:0},{r:1,c:1},{r:0,c:3},{r:2,c:3},{r:4,c:4},{r:5,c:5}]);assert(sat(P,'A',{type:'aloneWithPerson',person:'B'},a));a.C={r:1,c:2};assert(!sat(P,'A',{type:'aloneWithPerson',person:'B'},a));a.B={r:0,c:3};assert(!sat(P,'A',{type:'aloneWithPerson',person:'B'},a))});
t('westOfPerson arc propagation trace',()=>{let P=base();P.clues.A=[{type:'westOfPerson',person:'B'}];let D={A:new Set([0,4]),B:new Set([7,9]),C:new Set([14,15]),D:new Set([20,21]),E:new Set([28,29]),F:new Set([34,35])},r=E.propagateDomains(P,D);assert.deepEqual([...r.domains.A],[0]);let e=r.events.find(e=>e.reason==='relational'&&e.clueType==='westOfPerson'&&e.subject==='A');assert(e&&e.removed.some(x=>x.r===0&&x.c===4)&&e.before.length===2&&e.after.length===1)});
t('onlyOnObject propagation',()=>{let P=base();P.objects=[{name:'O',r:0,c:0},{name:'O',r:2,c:2}];P.clues.A=[{type:'onlyOnObject',object:'O'}];let D={A:new Set([0,14]),B:new Set([7,14]),C:new Set([2,14]),D:new Set([20,21]),E:new Set([28,29]),F:new Set([34,35])},r=E.propagateDomains(P,D);assert(!r.domains.B.has(14)&&!r.domains.C.has(14));assert(r.events.some(e=>e.clueType==='onlyOnObject'))});
t('alone propagation',()=>{let P=base();P.clues.A=[{type:'alone'}];let D={A:new Set([0]),B:new Set([7,9]),C:new Set([14,15]),D:new Set([20,21]),E:new Set([28,29]),F:new Set([34,35])},r=E.propagateDomains(P,D);assert(!r.domains.B.has(7));assert(r.events.some(e=>e.clueType==='alone'&&e.subject==='B'))});
t('aloneWithPerson propagation',()=>{let P=base();P.clues.A=[{type:'aloneWithPerson',person:'B'}];let D={A:new Set([0]),B:new Set([7,9]),C:new Set([2,14]),D:new Set([20,21]),E:new Set([28,29]),F:new Set([34,35])},r=E.propagateDomains(P,D);assert.deepEqual([...r.domains.B],[7]);assert(!r.domains.C.has(2));assert(r.events.some(e=>e.clueType==='aloneWithPerson'))});
t('human path zero backtracking calls',()=>{let P=base();P.solution=A;P.clues={A:[{type:'row',row:0},{type:'column',column:0}],B:[{type:'row',row:1},{type:'column',column:1}],C:[{type:'row',row:2},{type:'column',column:2}],D:[{type:'row',row:3},{type:'column',column:3}],E:[{type:'row',row:4},{type:'column',column:4}],F:[{type:'victim'}]};E.resetSearchCallCount();E.strictSolve(P);assert.equal(E.getSearchCallCount(),0)});
console.log(`SEMANTIC TESTS PASSED: ${n}`);
