const assert=require('assert'),E=require('../engine/easy-6x6-profiles.js');
const R=E.regionGrid(),base=()=>({people:[...E.PEOPLE],victim:'F',profile:'easy-1',regionOf:R,roomNames:['R1','R2','R3','R4','R5','R6'],objects:[],clues:{},globalRules:[],solution:{A:{r:0,c:0},B:{r:1,c:1},C:{r:2,c:2},D:{r:3,c:3},E:{r:4,c:4},F:{r:5,c:5}}});
let passed=0;function t(name,fn){fn();passed++;console.log('PASS',name)}
function obj(name,blocking,size,occ){return{id:name.toLowerCase().replace(/ /g,'-'),name,icon:blocking?'L1':'1',blocking,footprintSize:size,occurrences:occ.map(cells=>({cells}))}}
t('two separate single-cell occurrences share size 1',()=>{let P=base();P.objects=[obj('Object 1',false,1,[[{r:0,c:0}],[{r:4,c:4}]])];assert(E.validateObjects(P));assert.equal(E.objectOccurrences(P,'Object 1').length,2);assert.deepEqual(E.objectOccurrences(P,'Object 1').map(x=>x.cells.length),[1,1])});
t('mixed-size repeated occurrences are rejected',()=>{let P=base();P.objects=[obj('Object 1',false,2,[[{r:0,c:0},{r:0,c:1}],[{r:4,c:4}]])];assert(!E.validateObjects(P))});
t('repeated 2-cell occurrences may use different orientations',()=>{let P=base();P.objects=[obj('Object 1',false,2,[[{r:0,c:0},{r:0,c:1}],[{r:4,c:4},{r:5,c:4}]])];assert(E.validateObjects(P));assert.deepEqual(E.objectOccurrences(P,'Object 1').map(x=>x.cells.length),[2,2])});
t('Locked multiple occurrences use one fixed size',()=>{let P=base();P.objects=[obj('Locked 1',true,2,[[{r:0,c:0},{r:0,c:1}],[{r:4,c:4},{r:5,c:4}]])];assert(E.validateObjects(P))});
t('onObject accepts either occurrence',()=>{let P=base();P.objects=[obj('Object 1',false,1,[[{r:0,c:0}],[{r:4,c:4}]])];assert(E.unaryHolds(P,{type:'onObject',object:'Object 1'},{r:0,c:0}));assert(E.unaryHolds(P,{type:'onObject',object:'Object 1'},{r:4,c:4}))});
t('onlyOnObject spans all occurrences',()=>{let P=base();P.objects=[obj('Object 1',false,1,[[{r:0,c:0}],[{r:4,c:4}]])];P.clues.A=[{type:'onlyOnObject',object:'Object 1'}];let a={...P.solution};a.A={r:0,c:0};a.E={r:4,c:4};assert(!E.clueSatisfied(P,'A',P.clues.A[0],a));a.E={r:4,c:3};assert(E.clueSatisfied(P,'A',P.clues.A[0],a))});
t('beside either occurrence and respects wall',()=>{let P=base();P.objects=[obj('Object 1',false,1,[[{r:0,c:2}],[{r:4,c:4}]])];assert(E.besideObject(P,{r:0,c:1},'Object 1'));assert(E.besideObject(P,{r:4,c:3},'Object 1'));assert(!E.besideObject(P,{r:0,c:3},'Object 1'))});
t('diagonal either occurrence',()=>{let P=base();P.objects=[obj('Object 1',false,1,[[{r:0,c:0}],[{r:4,c:4}]])];assert(E.unaryHolds(P,{type:'diagonal',object:'Object 1'},{r:1,c:1}));assert(E.unaryHolds(P,{type:'diagonal',object:'Object 1'},{r:5,c:3}))});
t('directions accept any physical occurrence',()=>{let P=base();P.objects=[obj('Object 1',false,1,[[{r:1,c:1}],[{r:4,c:4}]])];assert(E.unaryHolds(P,{type:'westOfObject',object:'Object 1'},{r:2,c:0}));assert(E.unaryHolds(P,{type:'eastOfObject',object:'Object 1'},{r:2,c:5}));assert(E.unaryHolds(P,{type:'northOfObject',object:'Object 1'},{r:0,c:2}));assert(E.unaryHolds(P,{type:'southOfObject',object:'Object 1'},{r:5,c:2}))});
t('every 3-cell occurrence stays connected at its fixed size',()=>{let P=base();P.objects=[obj('Object 1',false,3,[[{r:0,c:0},{r:0,c:1},{r:1,c:1}],[{r:4,c:3},{r:4,c:4},{r:5,c:4}]])];assert(E.validateObjects(P));assert.deepEqual(E.objectOccurrences(P,'Object 1').map(x=>x.cells.length),[3,3])});
t('separate disconnected occurrences are not one disconnected footprint',()=>{let P=base();P.objects=[obj('Object 1',false,1,[[{r:0,c:0}],[{r:4,c:4}]])];assert(E.validObject(P,P.objects[0]));P.objects=[obj('Object 1',false,2,[[{r:0,c:0},{r:0,c:2}]])];assert(!E.validObject(P,P.objects[0]))});
t('every Locked occurrence blocks every cell',()=>{let P=base();P.objects=[obj('Locked 1',true,2,[[{r:0,c:0},{r:0,c:1}],[{r:4,c:4},{r:5,c:4}]])];for(const x of E.objectCells(P,'Locked 1'))assert(E.blockedCell(P,x));assert(!E.blockedCell(P,{r:3,c:3}))});
function seedHash(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function seededRandom(seed){let a=seedHash(seed);return()=>{a|=0;a=a+0x6D2B79F5|0;let q=Math.imul(a^a>>>15,1|a);q=q+Math.imul(q^q>>>7,61|q)^q;return((q^q>>>14)>>>0)/4294967296}}function gen(id){let old=Math.random;Math.random=seededRandom(id);try{let pr=['easy-1','easy-2','easy-3'][Math.floor(Math.random()*3)];return E.generate(pr,6000)}finally{Math.random=old}}
t('seeded Puzzle ID preserves IDs sizes occurrences footprints exactly',()=>{let a=gen('REPEAT-ID-TEST'),b=gen('REPEAT-ID-TEST');assert(a&&b);let pick=P=>P.objects.map(o=>({id:o.id,name:o.name,blocking:o.blocking,footprintSize:o.footprintSize,occurrences:E.objectOccurrences(P,o.name)}));assert.deepEqual(pick(a),pick(b));for(const o of a.objects)assert(E.objectOccurrences(a,o.name).every(q=>q.cells.length===o.footprintSize))});
console.log(`REPEATED OBJECT SEMANTIC TESTS PASSED: ${passed}`);