from pathlib import Path
p=Path('engine/easy-6x6-profiles.js')
s=p.read_text()
old="function objectByName(P,n){return P.objects.find(o=>o.name===n)}function objectCells(P,n){let o=objectByName(P,n);if(!o)return[];if(Array.isArray(o.cells))return o.cells;return Number.isInteger(o.r)&&Number.isInteger(o.c)?[{r:o.r,c:o.c}]:[]}function objectExtent(P,n){let cs=objectCells(P,n);if(!cs.length)return null;return{minR:Math.min(...cs.map(x=>x.r)),maxR:Math.max(...cs.map(x=>x.r)),minC:Math.min(...cs.map(x=>x.c)),maxC:Math.max(...cs.map(x=>x.c))}}"
new="function objectByName(P,n){return P.objects.find(o=>o.name===n)}function objectOccurrences(P,n){let o=typeof n==='string'?objectByName(P,n):n;if(!o)return[];if(Array.isArray(o.occurrences))return o.occurrences.map(q=>({cells:Array.isArray(q.cells)?q.cells:[]}));if(Array.isArray(o.cells))return[{cells:o.cells}];return Number.isInteger(o.r)&&Number.isInteger(o.c)?[{cells:[{r:o.r,c:o.c}]}]:[]}function objectCells(P,n){return objectOccurrences(P,n).flatMap(q=>q.cells)}function objectExtent(P,n){let cs=objectCells(P,n);if(!cs.length)return null;return{minR:Math.min(...cs.map(x=>x.r)),maxR:Math.max(...cs.map(x=>x.r)),minC:Math.min(...cs.map(x=>x.c)),maxC:Math.max(...cs.map(x=>x.c))}}"
assert old in s
s=s.replace(old,new)
old="function validObject(P,o,others=[]){let cs=Array.isArray(o.cells)?o.cells:(Number.isInteger(o.r)&&Number.isInteger(o.c)?[{r:o.r,c:o.c}]:[]);if(cs.length<1||cs.length>3)return false;if(cs.some(x=>x.r<0||x.r>=N||x.c<0||x.c>=N))return false;if(new Set(cs.map(x=>idx(x.r,x.c))).size!==cs.length)return false;let seen=new Set([idx(cs[0].r,cs[0].c)]),stack=[cs[0]];while(stack.length){let a=stack.pop();for(const b of cs)if(!seen.has(idx(b.r,b.c))&&Math.abs(a.r-b.r)+Math.abs(a.c-b.c)===1){seen.add(idx(b.r,b.c));stack.push(b)}}if(seen.size!==cs.length)return false;let rid=room(P,cs[0]);if(cs.some(x=>room(P,x)!==rid))return false;for(const q of others)if(objectCells({objects:[q]},q.name).some(a=>cs.some(b=>same(a,b))))return false;return true}\nfunction validateObjects(P){for(let i=0;i<P.objects.length;i++)if(!validObject(P,P.objects[i],P.objects.slice(0,i)))return false;return true}function blockedCell(P,x){return P.objects.some(o=>o.blocking===true&&objectCells(P,o.name).some(c=>same(c,x)))}"
new="function validFootprint(P,cs){if(cs.length<1||cs.length>3)return false;if(cs.some(x=>x.r<0||x.r>=N||x.c<0||x.c>=N))return false;if(new Set(cs.map(x=>idx(x.r,x.c))).size!==cs.length)return false;let seen=new Set([idx(cs[0].r,cs[0].c)]),stack=[cs[0]];while(stack.length){let a=stack.pop();for(const b of cs)if(!seen.has(idx(b.r,b.c))&&Math.abs(a.r-b.r)+Math.abs(a.c-b.c)===1){seen.add(idx(b.r,b.c));stack.push(b)}}if(seen.size!==cs.length)return false;let rid=room(P,cs[0]);return !cs.some(x=>room(P,x)!==rid)}function validObject(P,o,others=[]){let occ=objectOccurrences(P,o);if(!occ.length||occ.some(q=>!validFootprint(P,q.cells)))return false;let all=occ.flatMap(q=>q.cells);if(new Set(all.map(x=>idx(x.r,x.c))).size!==all.length)return false;let occupied=new Set(others.flatMap(q=>objectCells({objects:[q]},q.name)).map(x=>idx(x.r,x.c)));return !all.some(x=>occupied.has(idx(x.r,x.c)))}\nfunction validateObjects(P){for(let i=0;i<P.objects.length;i++)if(!validObject(P,P.objects[i],P.objects.slice(0,i)))return false;return true}function blockedCell(P,x){return P.objects.some(o=>o.blocking===true&&objectCells(P,o.name).some(c=>same(c,x)))}"
assert old in s
s=s.replace(old,new)
start=s.index('function makeObjects(P){')
end=s.index('\nfunction factPool(P,p)',start)
newmake='''function makeObjects(P){let used=new Set(),wanted=7+rand(3),normalN=0,lockedN=0;function addOccurrence(blocking,cells){let pool=P.objects.filter(o=>o.blocking===blocking),reuse=pool.length&&Math.random()<.32,o=reuse?pool[rand(pool.length)]:null;if(!o){let n=blocking?++lockedN:++normalN,name=(blocking?'Locked ':'Object ')+n;o={id:(blocking?'locked-':'object-')+n,name,icon:(blocking?'L':'')+n,occurrences:[],blocking};P.objects.push(o)}o.occurrences.push({cells:cells.map(x=>({r:x.r,c:x.c}))})}for(let i=0;i<wanted;i++){let blocking=Math.random()<.38,free=shuffle([...Array(N*N).keys()]).map(cell).filter(x=>!used.has(idx(x.r,x.c))&&(!blocking||!PEOPLE.some(p=>same(P.solution[p],x))));if(!free.length)break;let roll=Math.random(),size=roll<.55?1:roll<.88?2:3,start=free[0],cells=growFootprint(P,start,size,used);if(cells.length<size)cells=[start];if(blocking&&cells.some(x=>PEOPLE.some(p=>same(P.solution[p],x)))){i--;continue}cells.forEach(x=>used.add(idx(x.r,x.c)));addOccurrence(blocking,cells)}for(const p of BASE){let x=P.solution[p];if(!P.objects.some(o=>objectCells(P,o.name).some(c=>same(c,x)))&&Math.random()<.35&&!used.has(idx(x.r,x.c))){addOccurrence(false,[x]);used.add(idx(x.r,x.c))}}}'''
s=s[:start]+newmake+s[end:]
s=s.replace("if(room(P,x)===room(P,cs[0])&&!besideObject(P,x,o.name))add('roomNotBesideObject'","if(cs.some(z=>room(P,x)===room(P,z))&&!besideObject(P,x,o.name))add('roomNotBesideObject'")
s=s.replace('regionGrid,adjacent,isCorner,objectByName,objectCells,objectExtent,besideObject,validObject,validateObjects,blockedCell','regionGrid,adjacent,isCorner,objectByName,objectOccurrences,objectCells,objectExtent,besideObject,validObject,validateObjects,blockedCell')
p.write_text(s)
p=Path('index.html');s=p.read_text()
s=s.replace('`<b>CASE SOLVED ✅</b> — ${P.culprit} was the culprit.`',"'<b>Puzzle solved!</b>'")
old="let o=P.objects.find(o=>E.objectCells(P,o.name).some(x=>same(x,here)));if(o){let fp=document.createElement('span');fp.className='object-footprint';let cs=E.objectCells(P,o.name),has=(rr,cc)=>cs.some(x=>x.r===rr&&x.c===cc);if(has(r,c-1))fp.style.borderLeft='0';if(has(r,c+1))fp.style.borderRight='0';if(has(r-1,c))fp.style.borderTop='0';if(has(r+1,c))fp.style.borderBottom='0';if(o.blocking)fp.classList.add('locked-footprint');d.appendChild(fp);if(same(here,cs[0])){let s=document.createElement('span');s.className='object';s.textContent=o.icon;d.appendChild(s)}}"
new="let o=P.objects.find(o=>E.objectCells(P,o.name).some(x=>same(x,here)));if(o){let occ=E.objectOccurrences(P,o.name).find(q=>q.cells.some(x=>same(x,here))),cs=occ.cells,fp=document.createElement('span');fp.className='object-footprint';let has=(rr,cc)=>cs.some(x=>x.r===rr&&x.c===cc);if(has(r,c-1))fp.style.borderLeft='0';if(has(r,c+1))fp.style.borderRight='0';if(has(r-1,c))fp.style.borderTop='0';if(has(r+1,c))fp.style.borderBottom='0';if(o.blocking)fp.classList.add('locked-footprint');d.appendChild(fp);if(same(here,cs[0])){let s=document.createElement('span');s.className='object';s.textContent=o.icon;d.appendChild(s)}}"
assert old in s
s=s.replace(old,new)
s=s.replace("objects:P.objects.map(o=>({id:o.id,name:o.name,blocking:!!o.blocking,cells:E.objectCells(P,o.name)}))","objects:P.objects.map(o=>({id:o.id,name:o.name,blocking:!!o.blocking,occurrences:E.objectOccurrences(P,o.name)}))")
p.write_text(s)
