from pathlib import Path
import re

src_path=Path('engine/easy-6x6-profiles.js')
out_path=Path('engine/medium-7x7.js')
s=src_path.read_text()

s=s.replace('root.Easy6Engine=api','root.Medium7Engine=api')
s=s.replace("const N=6,PEOPLE=['A','B','C','D','E','F'],VICTIM='F',BASE=PEOPLE.filter(p=>p!==VICTIM);","const N=7,PEOPLE=['A','B','C','D','E','F','G'],VICTIM='G',BASE=PEOPLE.filter(p=>p!==VICTIM);")
s=re.sub(r"const PROFILES=.*?;\nconst CLUE_TYPES", "const PROFILES={'medium':{id:'medium',label:'Medium 7×7'}};\nconst CLUE_TYPES", s, count=1, flags=re.S)

needle="const rand=n=>Math.floor(Math.random()*n);function shuffle(a){a=a.slice();for(let i=a.length-1;i;i--){let j=rand(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}const same=(a,b)=>a&&b&&a.r===b.r&&a.c===b.c,idx=(r,c)=>r*N+c,cell=i=>({r:Math.floor(i/N),c:i%N});"
insert=needle+"\nfunction seedHash(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function seededRandom(seed){let a=seedHash(seed);return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}function withSeed(seed,fn){const old=Math.random;Math.random=seededRandom(String(seed));try{return fn()}finally{Math.random=old}}"
assert needle in s
s=s.replace(needle,insert,1)

solver=r'''function baseDomainSet(P){return new Set(baseCandidates(P).map(x=>idx(x.r,x.c)))}
function initialDomainsWithTrace(P){let D={},events=[];for(const p of PEOPLE)D[p]=baseDomainSet(P);for(const p of PEOPLE)for(const cl of clueList(P,p)){let bad=new Set([...D[p]].filter(i=>!unaryHolds(P,cl,cell(i))));remove(D,p,bad,'own-clue-filtering',cl,events,{phase:'own'});}events.forEach(e=>e.round=0);return{domains:D,events}}
function domainsFromPuzzle(P){return initialDomainsWithTrace(P).domains}function cloneDomains(D){return Object.fromEntries(Object.entries(D).map(([p,s])=>[p,new Set(s)]))}
function remove(D,p,ids,reason,cl,events,meta={}){let before=[...D[p]],rm=before.filter(i=>ids.has(i));if(!rm.length)return false;rm.forEach(i=>D[p].delete(i));events.push({reason,clueType:cl?.type||null,subject:p,removed:rm.map(cell),before:before.map(cell),after:[...D[p]].map(cell),...meta});if(before.length>1&&D[p].size===1){events.push({reason:'forced-placement',subject:p,cell:cell([...D[p]][0]),sourceReason:reason,clueType:cl?.type||null,...meta})}return true}
function propagateBinary(P,D,subject,cl,events){let ref=cl.person;if(!D[ref])return false;let changed=false;let badA=new Set([...D[subject]].filter(ai=>![...D[ref]].some(bi=>binaryHolds(P,cl.type,cell(ai),cell(bi))))),badB=new Set([...D[ref]].filter(bi=>![...D[subject]].some(ai=>binaryHolds(P,cl.type,cell(ai),cell(bi)))));if(remove(D,subject,badA,'relational-deduction',cl,events,{reference:ref}))changed=true;if(remove(D,ref,badB,'relational-deduction',cl,events,{reference:subject}))changed=true;return changed}
function propagateCardinality(P,D,subject,cl,events){let changed=false;if(cl.type==='onlyOnObject'){let obj=new Set(objectCells(P,cl.object).map(o=>idx(o.r,o.c)));for(const q of PEOPLE)if(q!==subject&&remove(D,q,new Set([...D[q]].filter(i=>obj.has(i))),'relational-deduction',cl,events,{reference:subject}))changed=true;return changed}if(cl.type==='alone'||cl.type==='aloneInRooms'){let impossible=new Set;for(const ai of D[subject]){let rid=room(P,cell(ai)),blocked=PEOPLE.some(q=>q!==subject&&[...D[q]].every(bi=>room(P,cell(bi))===rid));if(blocked)impossible.add(ai)}if(remove(D,subject,impossible,'relational-deduction',cl,events))changed=true;let rooms=[...new Set([...D[subject]].map(i=>room(P,cell(i))))];if(rooms.length===1){let rid=rooms[0];for(const q of PEOPLE)if(q!==subject&&remove(D,q,new Set([...D[q]].filter(i=>room(P,cell(i))===rid)),'relational-deduction',cl,events,{reference:subject,room:rid}))changed=true}return changed}if(cl.type==='aloneWithPerson'){let ref=cl.person;if(propagateBinary(P,D,subject,cl,events))changed=true;let roomsA=new Set([...D[subject]].map(i=>room(P,cell(i)))),roomsB=new Set([...D[ref]].map(i=>room(P,cell(i)))),common=[...roomsA].filter(r=>roomsB.has(r));if(common.length===1){let rid=common[0];for(const q of PEOPLE)if(q!==subject&&q!==ref&&remove(D,q,new Set([...D[q]].filter(i=>room(P,cell(i))===rid)),'relational-deduction',cl,events,{reference:subject,room:rid}))changed=true}return changed}return false}
function combinations(a,k){let out=[];function rec(start,cur){if(cur.length===k){out.push(cur.slice());return}for(let i=start;i<=a.length-(k-cur.length);i++){cur.push(a[i]);rec(i+1,cur);cur.pop()}}rec(0,[]);return out}
function axisValues(D,p,axis){return new Set([...D[p]].map(i=>axis==='row'?cell(i).r:cell(i).c))}
function applyOwnership(P,D,axis,events){let changed=false;for(let k=2;k<PEOPLE.length;k++)for(const owners of combinations(PEOPLE,k)){if(owners.some(p=>D[p].size<2||axisValues(D,p,axis).size<2))continue;let values=new Set;owners.forEach(p=>axisValues(D,p,axis).forEach(v=>values.add(v)));if(values.size!==k)continue;let reason=axis==='row'?(k===2?'row-ownership':'multi-row-ownership'):(k===2?'column-ownership':'multi-column-ownership');for(const q of PEOPLE)if(!owners.includes(q)){let bad=new Set([...D[q]].filter(i=>values.has(axis==='row'?cell(i).r:cell(i).c)));if(remove(D,q,bad,reason,null,events,{owners:owners.slice(),values:[...values].sort((a,b)=>a-b),axis}))changed=true}}return changed}
function applyIntersectingSquare(P,D,events){let changed=false;for(const source of PEOPLE){if(D[source].size<2||D[source].size>3)continue;let supports=[...D[source]].map(cell);for(const q of PEOPLE)if(q!==source){let bad=new Set([...D[q]].filter(i=>{let y=cell(i);return supports.every(x=>x.r===y.r||x.c===y.c)}));if(remove(D,q,bad,'intersecting-square-elimination',null,events,{sourcePerson:source,supports}))changed=true}}return changed}
function propagateDomains(P,input=null){let init=input?{domains:cloneDomains(input),events:[]} : initialDomainsWithTrace(P),D=init.domains,events=init.events,changed=true,guard=0;while(changed&&guard++<100){changed=false;let roundStart=events.length;for(const p of PEOPLE)if(D[p].size===1){let x=cell([...D[p]][0]);for(const q of PEOPLE)if(q!==p){let rowBad=new Set([...D[q]].filter(i=>cell(i).r===x.r));if(remove(D,q,rowBad,'row-elimination',null,events,{sourcePerson:p,row:x.r}))changed=true;let colBad=new Set([...D[q]].filter(i=>cell(i).c===x.c));if(remove(D,q,colBad,'column-elimination',null,events,{sourcePerson:p,column:x.c}))changed=true}}for(const p of PEOPLE)for(const cl of clueList(P,p)){if(['notWithPerson','besidePerson','westOfPerson','eastOfPerson','northOfPerson','southOfPerson'].includes(cl.type)){if(propagateBinary(P,D,p,cl,events))changed=true}else if(['onlyOnObject','alone','aloneInRooms','aloneWithPerson'].includes(cl.type)){if(propagateCardinality(P,D,p,cl,events))changed=true}}for(let r=0;r<N;r++){let owners=PEOPLE.filter(p=>[...D[p]].some(i=>cell(i).r===r));if(owners.length===1){let p=owners[0],bad=new Set([...D[p]].filter(i=>cell(i).r!==r));if(remove(D,p,bad,'row-occupancy',null,events,{row:r}))changed=true}}for(let c=0;c<N;c++){let owners=PEOPLE.filter(p=>[...D[p]].some(i=>cell(i).c===c));if(owners.length===1){let p=owners[0],bad=new Set([...D[p]].filter(i=>cell(i).c!==c));if(remove(D,p,bad,'column-occupancy',null,events,{column:c}))changed=true}}if(applyIntersectingSquare(P,D,events))changed=true;if(applyOwnership(P,D,'row',events))changed=true;if(applyOwnership(P,D,'column',events))changed=true;for(let i=roundStart;i<events.length;i++)if(events[i].round===undefined)events[i].round=guard;if(PEOPLE.some(p=>D[p].size===0))break}return{domains:D,events,contradiction:PEOPLE.some(p=>D[p].size===0),solved:PEOPLE.every(p=>D[p].size===1),rounds:guard}}
function strictSolve(P){let beforeSearch=searchCalls,res=propagateDomains(P),afterSearch=searchCalls,trace=res.events;if(afterSearch!==beforeSearch)throw Error('Human propagation invoked backtracking');let placements={};if(res.solved)for(const p of PEOPLE)placements[p]=cell([...res.domains[p]][0]);let ok=res.solved&&!res.contradiction&&fullValid(P,placements);return{ok,reason:ok?'complete deterministic propagation':'No complete deterministic solve; guessing would be required',trace,placements,domains:res.domains,searchCalls:afterSearch-beforeSearch,rounds:res.rounds}}
'''
s,n=re.subn(r"function domainsFromPuzzle\(P\).*?function growFootprint",solver+"function growFootprint",s,count=1,flags=re.S)
assert n==1

medium=r'''function mediumClueOptions(P,p){let pool=factPool(P,p),out=[];function add(cs){let test={...P,clues:{...P.clues,[p]:cs}},coh=cluePairCoherence(test,p,cs);if(!coh.ok)return;let n=ownCandidates(test,p).length;if(n<2||n>9)return;let relational=cs.some(c=>!!c.person||['onlyOnObject','alone','aloneInRooms','aloneWithPerson'].includes(c.type));out.push({clues:cs,candidates:n,relational})}for(const c of pool)add([c]);for(let i=0;i<pool.length;i++)for(let j=i+1;j<pool.length;j++){if(pool[i].type==='onObject'&&pool[j].type==='onObject')continue;add([pool[i],pool[j]])}let seen=new Set;out=out.filter(o=>{let k=o.clues.map(c=>JSON.stringify(c)).sort().join('|');if(seen.has(k))return false;seen.add(k);return true});return shuffle(out).sort((a,b)=>(Math.abs(a.candidates-4)+(a.relational?0:1))-(Math.abs(b.candidates-4)+(b.relational?0:1))).slice(0,90)}
function buildCandidate(profileId='medium'){if(profileId!=='medium')return null;let R=generateRegionGrid();if(!R)return null;let solution=makeSolution(R);if(!solution)return null;let roomCount=Math.max(...R.flat())+1,P={profile:'medium',people:[...PEOPLE],victim:VICTIM,regionOf:R,roomNames:Array.from({length:roomCount},(_,i)=>'R'+(i+1)),solution,objects:[],clues:{},globalRules:[],objective:{type:'locatePerson',person:VICTIM}};makeObjects(P);if(!validateObjects(P))return null;let options={};for(const p of PEOPLE){options[p]=mediumClueOptions(P,p);if(!options[p].length)return null}for(let pick=1;pick<=320;pick++){let clues={},relTargets=new Set(shuffle(PEOPLE).slice(0,3)),on=0,failed=false;for(const p of shuffle(PEOPLE)){let preferred=relTargets.has(p)?options[p].filter(o=>o.relational):options[p];if(!preferred.length)preferred=options[p];let shortlist=preferred.slice(0,Math.min(28,preferred.length)),choice=shortlist[rand(shortlist.length)];clues[p]=choice.clues;on+=choice.clues.filter(c=>c.type==='onObject').length;if(on>2){failed=true;break}}if(failed)continue;P.clues=clues;let coherence=validateCluePairs(P);if(!coherence.ok)continue;let stored=validateStoredSolutionAgainstClues(P);if(!stored.valid)continue;let h=strictSolve(P);if(!h.ok)continue;let m=metrics(P,h),advanced=m.rowOwnershipDeductions+m.columnOwnershipDeductions+m.multiRowOwnershipDeductions+m.multiColumnOwnershipDeductions+m.intersectingSquareDeductions;if(m.directClueSingles<=1&&m.multiCandidatePeople>=6&&m.relationalDeductions>=1&&advanced>=1&&m.dependencyDepth>=2){P.selectionAttempts=pick;return P}}return null}
function metrics(P,h){let initialCandidates={};PEOPLE.forEach(p=>initialCandidates[p]=ownCandidates(P,p).length);let t=h?.trace||[],count=r=>t.filter(x=>x.reason===r).length;return{initialCandidates,directClueSingles:PEOPLE.filter(p=>initialCandidates[p]===1).length,multiCandidatePeople:PEOPLE.filter(p=>initialCandidates[p]>1).length,ownClueFilteringDeductions:count('own-clue-filtering'),rowColumnEliminations:count('row-elimination')+count('column-elimination'),rowEliminations:count('row-elimination'),columnEliminations:count('column-elimination'),rowColumnOccupancyDeductions:count('row-occupancy')+count('column-occupancy'),rowOwnershipDeductions:count('row-ownership'),columnOwnershipDeductions:count('column-ownership'),multiRowOwnershipDeductions:count('multi-row-ownership'),multiColumnOwnershipDeductions:count('multi-column-ownership'),relationalDeductions:count('relational-deduction'),intersectingSquareDeductions:count('intersecting-square-elimination'),forcedPlacements:count('forced-placement'),totalDeterministicTraceLength:t.length,dependencyDepth:Math.max(0,...t.map(x=>x.round||0)),clueFamilies:[...new Set(PEOPLE.flatMap(p=>clueList(P,p).map(c=>c.type)))].sort()}}
function validate(P){if(!P||P.people.length!==7||P.victim!=='G'||P.objective?.type!=='locatePerson'||P.objective?.person!=='G')return{ok:false,reason:'shape'};if(!validateObjects(P))return{ok:false,reason:'invalid object geometry'};if(P.globalRules?.length)return{ok:false,reason:'global rules forbidden'};if(P.people.some(p=>clueList(P,p).length>2))return{ok:false,reason:'too many clues'};let coherence=validateCluePairs(P);if(!coherence.ok){if(coherence.sameObjectIssues?.length)return{ok:false,reason:'misleading same-object clue pair',cluePairCoherence:coherence};return{ok:false,reason:'dead clue branch',cluePairCoherence:coherence}}let on=PEOPLE.flatMap(p=>clueList(P,p)).filter(c=>c.type==='onObject').length;if(on>2)return{ok:false,reason:'too many onObject clues'};let storedSolutionClues=validateStoredSolutionAgainstClues(P);if(!storedSolutionClues.valid)return{ok:false,reason:'stored solution clue mismatch',storedSolutionClues};if(!fullValid(P,P.solution))return{ok:false,reason:'stored solution invalid'};let h=strictSolve(P);if(!h.ok)return{ok:false,reason:h.reason,human:h};let solutions=countSolutions(P,2),m=metrics(P,h),advanced=m.rowOwnershipDeductions+m.columnOwnershipDeductions+m.multiRowOwnershipDeductions+m.multiColumnOwnershipDeductions+m.intersectingSquareDeductions;if(solutions!==1)return{ok:false,reason:'solution count '+solutions,solutions,metrics:m};if(m.directClueSingles>1)return{ok:false,reason:'too many direct clue singles',metrics:m};if(m.multiCandidatePeople<6)return{ok:false,reason:'too few multi-candidate people',metrics:m};if(m.relationalDeductions<1)return{ok:false,reason:'no meaningful relational deduction',metrics:m};if(advanced<1)return{ok:false,reason:'no advanced ownership/intersection deduction',metrics:m};if(m.dependencyDepth<2)return{ok:false,reason:'dependency depth too shallow',metrics:m};return{ok:true,reason:'validated',solutions,human:h,metrics:m}}
function generate(profileId='medium',maxAttempts=2500){let rejects={};for(let attempt=1;attempt<=maxAttempts;attempt++){let P=buildCandidate(profileId);if(!P){rejects['candidate build failed']=(rejects['candidate build failed']||0)+1;continue}let V=validate(P);if(V.ok){P.validation=V;P.generationAttempts=attempt;P.rejections=rejects;return P}rejects[V.reason]=(rejects[V.reason]||0)+1}return null}
function generateById(id,maxAttempts=2500){return withSeed(String(id).trim().toUpperCase(),()=>{let P=generate('medium',maxAttempts);if(P)P.puzzleId=String(id).trim().toUpperCase();return P})}
'''
s,n=re.subn(r"function buildCandidate\(profileId\).*?function getSearchCallCount",medium+"function getSearchCallCount",s,count=1,flags=re.S)
assert n==1

start=s.index('return{N,PEOPLE,VICTIM,BASE,PROFILES,CLUE_TYPES,RELATIONAL,')
end=s.index('};\n});',start)
exports="return{N,PEOPLE,VICTIM,BASE,PROFILES,CLUE_TYPES,RELATIONAL,generateRegionGrid,ownCandidates,countSolutions,strictSolve,metrics,validate,buildCandidate,generate,generateById,factPool,fullValid,clueSatisfied,unaryHolds,binaryHolds,domainsFromPuzzle,propagateDomains,applyOwnership,applyIntersectingSquare,getSearchCallCount,resetSearchCallCount,regionGrid,adjacent,isCorner,objectByName,objectOccurrences,objectCells,objectExtent,objectOccurrenceExtents,besideObject,validObject,validateObjects,blockedCell,baseCandidates,objectClueHoldsForOccurrence,sameObjectPairCoherence,cluePairCoherence,validateCluePairs,validatePlacementAgainstClues,validateStoredSolutionAgainstClues};"
s=s[:start]+exports+s[end+2:]

assert "const N=7" in s and "VICTIM='G'" in s
assert "root.Medium7Engine" in s
assert "function applyOwnership" in s and "function applyIntersectingSquare" in s
out_path.write_text(s)
