from pathlib import Path

path = Path('engine/medium-7x7.js')
s = path.read_text()

marker = "function buildCandidate(profileId='medium')"
assert marker in s
analysis = r'''const ADVANCED_REASONS=new Set(['row-ownership','column-ownership','multi-row-ownership','multi-column-ownership','intersecting-square-elimination']);
function advancedDeductionKey(e){if(!ADVANCED_REASONS.has(e.reason))return null;if(e.reason==='intersecting-square-elimination'){let supports=(e.supports||[]).map(x=>`${x.r},${x.c}`).sort().join(';');return`${e.reason}|${e.round||0}|${e.sourcePerson||''}|${supports}`}let owners=(e.owners||[]).slice().sort().join(','),values=(e.values||[]).slice().sort((a,b)=>a-b).join(',');return`${e.reason}|${e.round||0}|${owners}|${values}`}
function influenceSources(e){let out=new Set;if(e.sourcePerson)out.add(e.sourcePerson);if(e.reference)out.add(e.reference);if(Array.isArray(e.owners))e.owners.forEach(p=>out.add(p));return out}
function analyzeMediumStructure(P,h){let t=h?.trace||[],groups=new Map;for(let i=0;i<t.length;i++){let e=t[i],key=advancedDeductionKey(e);if(!key)continue;if(!groups.has(key))groups.set(key,{key,reason:e.reason,indices:[],targets:new Set,participants:new Set});let g=groups.get(key);g.indices.push(i);if(e.subject){g.targets.add(e.subject);g.participants.add(e.subject)}influenceSources(e).forEach(p=>g.participants.add(p))}let materialAdvancedDeductions=0,dependentPlacements=new Set,chainPeople=new Set,materialKeys=[];for(const g of groups.values()){let tainted=new Set(g.targets),localPeople=new Set(g.participants),localPlacements=new Set,contributed=false,start=Math.min(...g.indices);for(let i=start+1;i<t.length;i++){let e=t[i];if(advancedDeductionKey(e)===g.key)continue;if(e.reason==='forced-placement'&&tainted.has(e.subject)){contributed=true;localPlacements.add(e.subject);localPeople.add(e.subject)}let sources=influenceSources(e),sourceTainted=[...sources].some(p=>tainted.has(p));if(sourceTainted){contributed=true;sources.forEach(p=>localPeople.add(p));if(e.subject){localPeople.add(e.subject);tainted.add(e.subject)}}}if(contributed){materialAdvancedDeductions++;materialKeys.push(g.key);localPlacements.forEach(p=>dependentPlacements.add(p));localPeople.forEach(p=>chainPeople.add(p))}}let ownershipGroups=[...groups.values()].filter(g=>g.reason!=='intersecting-square-elimination').length,intersectionGroups=[...groups.values()].filter(g=>g.reason==='intersecting-square-elimination').length;return{advancedDeductionCount:groups.size,ownershipCount:ownershipGroups,intersectionCount:intersectionGroups,materialAdvancedDeductions,advancedDependentPlacements:dependentPlacements.size,advancedDependentPlacementPeople:[...dependentPlacements].sort(),multiPersonChainPeople:chainPeople.size,multiPersonChainParticipants:[...chainPeople].sort(),materialAdvancedKeys:materialKeys}}
function mediumAcceptance(m){let reasons=[];if(m.directClueSingles!==0)reasons.push('immediate direct single');if(m.multiCandidatePeople!==PEOPLE.length)reasons.push('not every person initially unresolved');if(m.advancedDeductionCount<2)reasons.push('fewer than two structural advanced deductions');if(m.materialAdvancedDeductions<1)reasons.push('no advanced deduction contributes downstream');if(m.advancedDependentPlacements<1)reasons.push('no later placement depends on advanced deduction');if(m.multiPersonChainPeople<2)reasons.push('no genuine multi-person dependency chain');if(m.dependencyDepth<2)reasons.push('dependency depth too shallow');return{ok:reasons.length===0,reasons}}
function classifyMedium(m){let a=mediumAcceptance(m);if(!a.ok)return'TOO EASY';if(m.materialAdvancedDeductions>=2&&m.advancedDependentPlacements>=2&&m.multiPersonChainPeople>=3&&(m.advancedDeductionCount>=3||m.dependencyDepth>=3))return'CLEAR MEDIUM';return'BORDERLINE'}
'''
s = s.replace(marker, analysis + marker, 1)

old_build = "let m=metrics(P,h),advanced=m.rowOwnershipDeductions+m.columnOwnershipDeductions+m.multiRowOwnershipDeductions+m.multiColumnOwnershipDeductions+m.intersectingSquareDeductions;if(m.directClueSingles<=1&&m.multiCandidatePeople>=6&&m.relationalDeductions>=1&&advanced>=1&&m.dependencyDepth>=2){P.selectionAttempts=pick;return P}"
new_build = "let m=metrics(P,h),accept=mediumAcceptance(m);if(accept.ok){P.selectionAttempts=pick;return P}"
assert old_build in s
s = s.replace(old_build, new_build, 1)

old_metrics = "function metrics(P,h){let initialCandidates={};PEOPLE.forEach(p=>initialCandidates[p]=ownCandidates(P,p).length);let t=h?.trace||[],count=r=>t.filter(x=>x.reason===r).length;return{initialCandidates,directClueSingles:PEOPLE.filter(p=>initialCandidates[p]===1).length,multiCandidatePeople:PEOPLE.filter(p=>initialCandidates[p]>1).length,ownClueFilteringDeductions:count('own-clue-filtering'),rowColumnEliminations:count('row-elimination')+count('column-elimination'),rowEliminations:count('row-elimination'),columnEliminations:count('column-elimination'),rowColumnOccupancyDeductions:count('row-occupancy')+count('column-occupancy'),rowOwnershipDeductions:count('row-ownership'),columnOwnershipDeductions:count('column-ownership'),multiRowOwnershipDeductions:count('multi-row-ownership'),multiColumnOwnershipDeductions:count('multi-column-ownership'),relationalDeductions:count('relational-deduction'),intersectingSquareDeductions:count('intersecting-square-elimination'),forcedPlacements:count('forced-placement'),totalDeterministicTraceLength:t.length,dependencyDepth:Math.max(0,...t.map(x=>x.round||0)),clueFamilies:[...new Set(PEOPLE.flatMap(p=>clueList(P,p).map(c=>c.type)))].sort()}}"
new_metrics = "function metrics(P,h){let initialCandidates={};PEOPLE.forEach(p=>initialCandidates[p]=ownCandidates(P,p).length);let t=h?.trace||[],count=r=>t.filter(x=>x.reason===r).length,base={initialCandidates,directClueSingles:PEOPLE.filter(p=>initialCandidates[p]===1).length,multiCandidatePeople:PEOPLE.filter(p=>initialCandidates[p]>1).length,ownClueFilteringDeductions:count('own-clue-filtering'),rowColumnEliminations:count('row-elimination')+count('column-elimination'),rowEliminations:count('row-elimination'),columnEliminations:count('column-elimination'),rowColumnOccupancyDeductions:count('row-occupancy')+count('column-occupancy'),rowOwnershipDeductions:count('row-ownership'),columnOwnershipDeductions:count('column-ownership'),multiRowOwnershipDeductions:count('multi-row-ownership'),multiColumnOwnershipDeductions:count('multi-column-ownership'),relationalDeductions:count('relational-deduction'),intersectingSquareDeductions:count('intersecting-square-elimination'),forcedPlacements:count('forced-placement'),totalDeterministicTraceLength:t.length,dependencyDepth:Math.max(0,...t.map(x=>x.round||0)),clueFamilies:[...new Set(PEOPLE.flatMap(p=>clueList(P,p).map(c=>c.type)))].sort()};return{...base,...analyzeMediumStructure(P,h)}}"
assert old_metrics in s
s = s.replace(old_metrics, new_metrics, 1)

old_validate = "let h=strictSolve(P);if(!h.ok)return{ok:false,reason:h.reason,human:h};let solutions=countSolutions(P,2),m=metrics(P,h),advanced=m.rowOwnershipDeductions+m.columnOwnershipDeductions+m.multiRowOwnershipDeductions+m.multiColumnOwnershipDeductions+m.intersectingSquareDeductions;if(solutions!==1)return{ok:false,reason:'solution count '+solutions,solutions,metrics:m};if(m.directClueSingles>1)return{ok:false,reason:'too many direct clue singles',metrics:m};if(m.multiCandidatePeople<6)return{ok:false,reason:'too few multi-candidate people',metrics:m};if(m.relationalDeductions<1)return{ok:false,reason:'no meaningful relational deduction',metrics:m};if(advanced<1)return{ok:false,reason:'no advanced ownership/intersection deduction',metrics:m};if(m.dependencyDepth<2)return{ok:false,reason:'dependency depth too shallow',metrics:m};return{ok:true,reason:'validated',solutions,human:h,metrics:m}"
new_validate = "let h=strictSolve(P);if(!h.ok)return{ok:false,reason:h.reason,human:h};let solutions=countSolutions(P,2),m=metrics(P,h),accept=mediumAcceptance(m);if(solutions!==1)return{ok:false,reason:'solution count '+solutions,solutions,metrics:m};if(!accept.ok)return{ok:false,reason:'medium structure: '+accept.reasons.join('; '),metrics:m,mediumAcceptance:accept};return{ok:true,reason:'validated',solutions,human:h,metrics:m,mediumAcceptance:accept,mediumClassification:classifyMedium(m)}"
assert old_validate in s
s = s.replace(old_validate, new_validate, 1)

old_export = "propagateDomains,applyOwnership,applyIntersectingSquare,getSearchCallCount"
new_export = "propagateDomains,applyOwnership,applyIntersectingSquare,analyzeMediumStructure,mediumAcceptance,classifyMedium,getSearchCallCount"
assert old_export in s
s = s.replace(old_export, new_export, 1)

path.write_text(s)
